package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for ElsticEnergy kernel
var ElsticEnergy_code cu.Function

// Stores the arguments for ElsticEnergy kernel invocation
type ElsticEnergy_args_t struct{
	 arg_energy unsafe.Pointer
	 arg_exx unsafe.Pointer
	 arg_eyy unsafe.Pointer
	 arg_ezz unsafe.Pointer
	 arg_exy unsafe.Pointer
	 arg_eyz unsafe.Pointer
	 arg_exz unsafe.Pointer
	 arg_Nx int
	 arg_Ny int
	 arg_Nz int
	 arg_C1_ unsafe.Pointer
	 arg_C1_mul float32
	 arg_C2_ unsafe.Pointer
	 arg_C2_mul float32
	 arg_C3_ unsafe.Pointer
	 arg_C3_mul float32
	 argptr [16]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for ElsticEnergy kernel invocation
var ElsticEnergy_args ElsticEnergy_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 ElsticEnergy_args.argptr[0] = unsafe.Pointer(&ElsticEnergy_args.arg_energy)
	 ElsticEnergy_args.argptr[1] = unsafe.Pointer(&ElsticEnergy_args.arg_exx)
	 ElsticEnergy_args.argptr[2] = unsafe.Pointer(&ElsticEnergy_args.arg_eyy)
	 ElsticEnergy_args.argptr[3] = unsafe.Pointer(&ElsticEnergy_args.arg_ezz)
	 ElsticEnergy_args.argptr[4] = unsafe.Pointer(&ElsticEnergy_args.arg_exy)
	 ElsticEnergy_args.argptr[5] = unsafe.Pointer(&ElsticEnergy_args.arg_eyz)
	 ElsticEnergy_args.argptr[6] = unsafe.Pointer(&ElsticEnergy_args.arg_exz)
	 ElsticEnergy_args.argptr[7] = unsafe.Pointer(&ElsticEnergy_args.arg_Nx)
	 ElsticEnergy_args.argptr[8] = unsafe.Pointer(&ElsticEnergy_args.arg_Ny)
	 ElsticEnergy_args.argptr[9] = unsafe.Pointer(&ElsticEnergy_args.arg_Nz)
	 ElsticEnergy_args.argptr[10] = unsafe.Pointer(&ElsticEnergy_args.arg_C1_)
	 ElsticEnergy_args.argptr[11] = unsafe.Pointer(&ElsticEnergy_args.arg_C1_mul)
	 ElsticEnergy_args.argptr[12] = unsafe.Pointer(&ElsticEnergy_args.arg_C2_)
	 ElsticEnergy_args.argptr[13] = unsafe.Pointer(&ElsticEnergy_args.arg_C2_mul)
	 ElsticEnergy_args.argptr[14] = unsafe.Pointer(&ElsticEnergy_args.arg_C3_)
	 ElsticEnergy_args.argptr[15] = unsafe.Pointer(&ElsticEnergy_args.arg_C3_mul)
	 }

// Wrapper for ElsticEnergy CUDA kernel, asynchronous.
func k_ElsticEnergy_async ( energy unsafe.Pointer, exx unsafe.Pointer, eyy unsafe.Pointer, ezz unsafe.Pointer, exy unsafe.Pointer, eyz unsafe.Pointer, exz unsafe.Pointer, Nx int, Ny int, Nz int, C1_ unsafe.Pointer, C1_mul float32, C2_ unsafe.Pointer, C2_mul float32, C3_ unsafe.Pointer, C3_mul float32,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("ElsticEnergy")
	}

	ElsticEnergy_args.Lock()
	defer ElsticEnergy_args.Unlock()

	if ElsticEnergy_code == 0{
		ElsticEnergy_code = fatbinLoad(ElsticEnergy_map, "ElsticEnergy")
	}

	 ElsticEnergy_args.arg_energy = energy
	 ElsticEnergy_args.arg_exx = exx
	 ElsticEnergy_args.arg_eyy = eyy
	 ElsticEnergy_args.arg_ezz = ezz
	 ElsticEnergy_args.arg_exy = exy
	 ElsticEnergy_args.arg_eyz = eyz
	 ElsticEnergy_args.arg_exz = exz
	 ElsticEnergy_args.arg_Nx = Nx
	 ElsticEnergy_args.arg_Ny = Ny
	 ElsticEnergy_args.arg_Nz = Nz
	 ElsticEnergy_args.arg_C1_ = C1_
	 ElsticEnergy_args.arg_C1_mul = C1_mul
	 ElsticEnergy_args.arg_C2_ = C2_
	 ElsticEnergy_args.arg_C2_mul = C2_mul
	 ElsticEnergy_args.arg_C3_ = C3_
	 ElsticEnergy_args.arg_C3_mul = C3_mul
	

	args := ElsticEnergy_args.argptr[:]
	cu.LaunchKernel(ElsticEnergy_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("ElsticEnergy")
	}
}

// maps compute capability on PTX code for ElsticEnergy kernel.
var ElsticEnergy_map = map[int]string{ 0: "" ,
30: ElsticEnergy_ptx_30 ,
35: ElsticEnergy_ptx_35 ,
37: ElsticEnergy_ptx_37 ,
50: ElsticEnergy_ptx_50 ,
52: ElsticEnergy_ptx_52 ,
53: ElsticEnergy_ptx_53 ,
60: ElsticEnergy_ptx_60 ,
61: ElsticEnergy_ptx_61 ,
70: ElsticEnergy_ptx_70 ,
75: ElsticEnergy_ptx_75  }

// ElsticEnergy PTX code for various compute capabilities.
const(
  ElsticEnergy_ptx_30 = `
.version 6.3
.target sm_30
.address_size 64

	// .globl	ElsticEnergy

.visible .entry ElsticEnergy(
	.param .u64 ElsticEnergy_param_0,
	.param .u64 ElsticEnergy_param_1,
	.param .u64 ElsticEnergy_param_2,
	.param .u64 ElsticEnergy_param_3,
	.param .u64 ElsticEnergy_param_4,
	.param .u64 ElsticEnergy_param_5,
	.param .u64 ElsticEnergy_param_6,
	.param .u32 ElsticEnergy_param_7,
	.param .u32 ElsticEnergy_param_8,
	.param .u32 ElsticEnergy_param_9,
	.param .u64 ElsticEnergy_param_10,
	.param .f32 ElsticEnergy_param_11,
	.param .u64 ElsticEnergy_param_12,
	.param .f32 ElsticEnergy_param_13,
	.param .u64 ElsticEnergy_param_14,
	.param .f32 ElsticEnergy_param_15
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<35>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<35>;


	ld.param.u64 	%rd1, [ElsticEnergy_param_0];
	ld.param.u64 	%rd2, [ElsticEnergy_param_1];
	ld.param.u64 	%rd3, [ElsticEnergy_param_2];
	ld.param.u64 	%rd4, [ElsticEnergy_param_3];
	ld.param.u64 	%rd5, [ElsticEnergy_param_4];
	ld.param.u64 	%rd6, [ElsticEnergy_param_5];
	ld.param.u64 	%rd7, [ElsticEnergy_param_6];
	ld.param.u32 	%r5, [ElsticEnergy_param_7];
	ld.param.u32 	%r6, [ElsticEnergy_param_8];
	ld.param.u32 	%r7, [ElsticEnergy_param_9];
	ld.param.u64 	%rd8, [ElsticEnergy_param_10];
	ld.param.f32 	%f32, [ElsticEnergy_param_11];
	ld.param.u64 	%rd9, [ElsticEnergy_param_12];
	ld.param.f32 	%f33, [ElsticEnergy_param_13];
	ld.param.u64 	%rd10, [ElsticEnergy_param_14];
	ld.param.f32 	%f34, [ElsticEnergy_param_15];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r14, %r15, %r16;
	setp.ge.s32	%p1, %r2, %r6;
	setp.ge.s32	%p2, %r1, %r5;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_8;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64	%p6, %rd8, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd11, %rd8;
	mul.wide.s32 	%rd12, %r4, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.f32 	%f10, [%rd13];
	mul.f32 	%f32, %f10, %f32;

BB0_3:
	setp.eq.s64	%p7, %rd9, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd14, %rd9;
	mul.wide.s32 	%rd15, %r4, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.f32 	%f11, [%rd16];
	mul.f32 	%f33, %f11, %f33;

BB0_5:
	setp.eq.s64	%p8, %rd10, 0;
	@%p8 bra 	BB0_7;

	cvta.to.global.u64 	%rd17, %rd10;
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.f32 	%f12, [%rd19];
	mul.f32 	%f34, %f12, %f34;

BB0_7:
	cvta.to.global.u64 	%rd20, %rd7;
	cvta.to.global.u64 	%rd21, %rd6;
	cvta.to.global.u64 	%rd22, %rd5;
	cvta.to.global.u64 	%rd23, %rd2;
	cvt.f64.f32	%fd1, %f32;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	mul.wide.s32 	%rd24, %r4, 4;
	add.s64 	%rd25, %rd23, %rd24;
	ld.global.f32 	%f13, [%rd25];
	cvta.to.global.u64 	%rd26, %rd3;
	add.s64 	%rd27, %rd26, %rd24;
	ld.global.f32 	%f14, [%rd27];
	mul.f32 	%f15, %f14, %f14;
	fma.rn.f32 	%f16, %f13, %f13, %f15;
	cvta.to.global.u64 	%rd28, %rd4;
	add.s64 	%rd29, %rd28, %rd24;
	ld.global.f32 	%f17, [%rd29];
	fma.rn.f32 	%f18, %f17, %f17, %f16;
	cvt.f64.f32	%fd3, %f18;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64	%f19, %fd4;
	cvta.to.global.u64 	%rd30, %rd1;
	add.s64 	%rd31, %rd30, %rd24;
	mul.f32 	%f20, %f14, %f17;
	fma.rn.f32 	%f21, %f13, %f14, %f20;
	fma.rn.f32 	%f22, %f13, %f17, %f21;
	fma.rn.f32 	%f23, %f33, %f22, %f19;
	add.s64 	%rd32, %rd22, %rd24;
	ld.global.f32 	%f24, [%rd32];
	add.s64 	%rd33, %rd21, %rd24;
	ld.global.f32 	%f25, [%rd33];
	mul.f32 	%f26, %f25, %f25;
	fma.rn.f32 	%f27, %f24, %f24, %f26;
	add.s64 	%rd34, %rd20, %rd24;
	ld.global.f32 	%f28, [%rd34];
	fma.rn.f32 	%f29, %f28, %f28, %f27;
	add.f32 	%f30, %f34, %f34;
	fma.rn.f32 	%f31, %f30, %f29, %f23;
	st.global.f32 	[%rd31], %f31;

BB0_8:
	ret;
}


`
   ElsticEnergy_ptx_35 = `
.version 6.3
.target sm_35
.address_size 64

	// .globl	ElsticEnergy

.visible .entry ElsticEnergy(
	.param .u64 ElsticEnergy_param_0,
	.param .u64 ElsticEnergy_param_1,
	.param .u64 ElsticEnergy_param_2,
	.param .u64 ElsticEnergy_param_3,
	.param .u64 ElsticEnergy_param_4,
	.param .u64 ElsticEnergy_param_5,
	.param .u64 ElsticEnergy_param_6,
	.param .u32 ElsticEnergy_param_7,
	.param .u32 ElsticEnergy_param_8,
	.param .u32 ElsticEnergy_param_9,
	.param .u64 ElsticEnergy_param_10,
	.param .f32 ElsticEnergy_param_11,
	.param .u64 ElsticEnergy_param_12,
	.param .f32 ElsticEnergy_param_13,
	.param .u64 ElsticEnergy_param_14,
	.param .f32 ElsticEnergy_param_15
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<35>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<35>;


	ld.param.u64 	%rd1, [ElsticEnergy_param_0];
	ld.param.u64 	%rd2, [ElsticEnergy_param_1];
	ld.param.u64 	%rd3, [ElsticEnergy_param_2];
	ld.param.u64 	%rd4, [ElsticEnergy_param_3];
	ld.param.u64 	%rd5, [ElsticEnergy_param_4];
	ld.param.u64 	%rd6, [ElsticEnergy_param_5];
	ld.param.u64 	%rd7, [ElsticEnergy_param_6];
	ld.param.u32 	%r5, [ElsticEnergy_param_7];
	ld.param.u32 	%r6, [ElsticEnergy_param_8];
	ld.param.u32 	%r7, [ElsticEnergy_param_9];
	ld.param.u64 	%rd8, [ElsticEnergy_param_10];
	ld.param.f32 	%f32, [ElsticEnergy_param_11];
	ld.param.u64 	%rd9, [ElsticEnergy_param_12];
	ld.param.f32 	%f33, [ElsticEnergy_param_13];
	ld.param.u64 	%rd10, [ElsticEnergy_param_14];
	ld.param.f32 	%f34, [ElsticEnergy_param_15];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r14, %r15, %r16;
	setp.ge.s32	%p1, %r2, %r6;
	setp.ge.s32	%p2, %r1, %r5;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_8;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64	%p6, %rd8, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd11, %rd8;
	mul.wide.s32 	%rd12, %r4, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.nc.f32 	%f10, [%rd13];
	mul.f32 	%f32, %f10, %f32;

BB0_3:
	setp.eq.s64	%p7, %rd9, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd14, %rd9;
	mul.wide.s32 	%rd15, %r4, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f11, [%rd16];
	mul.f32 	%f33, %f11, %f33;

BB0_5:
	setp.eq.s64	%p8, %rd10, 0;
	@%p8 bra 	BB0_7;

	cvta.to.global.u64 	%rd17, %rd10;
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.nc.f32 	%f12, [%rd19];
	mul.f32 	%f34, %f12, %f34;

BB0_7:
	cvta.to.global.u64 	%rd20, %rd7;
	cvta.to.global.u64 	%rd21, %rd6;
	cvta.to.global.u64 	%rd22, %rd5;
	cvta.to.global.u64 	%rd23, %rd1;
	cvta.to.global.u64 	%rd24, %rd4;
	cvta.to.global.u64 	%rd25, %rd3;
	cvta.to.global.u64 	%rd26, %rd2;
	cvt.f64.f32	%fd1, %f32;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	mul.wide.s32 	%rd27, %r4, 4;
	add.s64 	%rd28, %rd26, %rd27;
	ld.global.nc.f32 	%f13, [%rd28];
	add.s64 	%rd29, %rd25, %rd27;
	ld.global.nc.f32 	%f14, [%rd29];
	mul.f32 	%f15, %f14, %f14;
	fma.rn.f32 	%f16, %f13, %f13, %f15;
	add.s64 	%rd30, %rd24, %rd27;
	ld.global.nc.f32 	%f17, [%rd30];
	fma.rn.f32 	%f18, %f17, %f17, %f16;
	cvt.f64.f32	%fd3, %f18;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64	%f19, %fd4;
	add.s64 	%rd31, %rd23, %rd27;
	mul.f32 	%f20, %f14, %f17;
	fma.rn.f32 	%f21, %f13, %f14, %f20;
	fma.rn.f32 	%f22, %f13, %f17, %f21;
	fma.rn.f32 	%f23, %f33, %f22, %f19;
	add.s64 	%rd32, %rd22, %rd27;
	ld.global.nc.f32 	%f24, [%rd32];
	add.s64 	%rd33, %rd21, %rd27;
	ld.global.nc.f32 	%f25, [%rd33];
	mul.f32 	%f26, %f25, %f25;
	fma.rn.f32 	%f27, %f24, %f24, %f26;
	add.s64 	%rd34, %rd20, %rd27;
	ld.global.nc.f32 	%f28, [%rd34];
	fma.rn.f32 	%f29, %f28, %f28, %f27;
	add.f32 	%f30, %f34, %f34;
	fma.rn.f32 	%f31, %f30, %f29, %f23;
	st.global.f32 	[%rd31], %f31;

BB0_8:
	ret;
}


`
   ElsticEnergy_ptx_37 = `
.version 6.3
.target sm_37
.address_size 64

	// .globl	ElsticEnergy

.visible .entry ElsticEnergy(
	.param .u64 ElsticEnergy_param_0,
	.param .u64 ElsticEnergy_param_1,
	.param .u64 ElsticEnergy_param_2,
	.param .u64 ElsticEnergy_param_3,
	.param .u64 ElsticEnergy_param_4,
	.param .u64 ElsticEnergy_param_5,
	.param .u64 ElsticEnergy_param_6,
	.param .u32 ElsticEnergy_param_7,
	.param .u32 ElsticEnergy_param_8,
	.param .u32 ElsticEnergy_param_9,
	.param .u64 ElsticEnergy_param_10,
	.param .f32 ElsticEnergy_param_11,
	.param .u64 ElsticEnergy_param_12,
	.param .f32 ElsticEnergy_param_13,
	.param .u64 ElsticEnergy_param_14,
	.param .f32 ElsticEnergy_param_15
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<35>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<35>;


	ld.param.u64 	%rd1, [ElsticEnergy_param_0];
	ld.param.u64 	%rd2, [ElsticEnergy_param_1];
	ld.param.u64 	%rd3, [ElsticEnergy_param_2];
	ld.param.u64 	%rd4, [ElsticEnergy_param_3];
	ld.param.u64 	%rd5, [ElsticEnergy_param_4];
	ld.param.u64 	%rd6, [ElsticEnergy_param_5];
	ld.param.u64 	%rd7, [ElsticEnergy_param_6];
	ld.param.u32 	%r5, [ElsticEnergy_param_7];
	ld.param.u32 	%r6, [ElsticEnergy_param_8];
	ld.param.u32 	%r7, [ElsticEnergy_param_9];
	ld.param.u64 	%rd8, [ElsticEnergy_param_10];
	ld.param.f32 	%f32, [ElsticEnergy_param_11];
	ld.param.u64 	%rd9, [ElsticEnergy_param_12];
	ld.param.f32 	%f33, [ElsticEnergy_param_13];
	ld.param.u64 	%rd10, [ElsticEnergy_param_14];
	ld.param.f32 	%f34, [ElsticEnergy_param_15];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r14, %r15, %r16;
	setp.ge.s32	%p1, %r2, %r6;
	setp.ge.s32	%p2, %r1, %r5;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_8;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64	%p6, %rd8, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd11, %rd8;
	mul.wide.s32 	%rd12, %r4, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.nc.f32 	%f10, [%rd13];
	mul.f32 	%f32, %f10, %f32;

BB0_3:
	setp.eq.s64	%p7, %rd9, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd14, %rd9;
	mul.wide.s32 	%rd15, %r4, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f11, [%rd16];
	mul.f32 	%f33, %f11, %f33;

BB0_5:
	setp.eq.s64	%p8, %rd10, 0;
	@%p8 bra 	BB0_7;

	cvta.to.global.u64 	%rd17, %rd10;
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.nc.f32 	%f12, [%rd19];
	mul.f32 	%f34, %f12, %f34;

BB0_7:
	cvta.to.global.u64 	%rd20, %rd7;
	cvta.to.global.u64 	%rd21, %rd6;
	cvta.to.global.u64 	%rd22, %rd5;
	cvta.to.global.u64 	%rd23, %rd1;
	cvta.to.global.u64 	%rd24, %rd4;
	cvta.to.global.u64 	%rd25, %rd3;
	cvta.to.global.u64 	%rd26, %rd2;
	cvt.f64.f32	%fd1, %f32;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	mul.wide.s32 	%rd27, %r4, 4;
	add.s64 	%rd28, %rd26, %rd27;
	ld.global.nc.f32 	%f13, [%rd28];
	add.s64 	%rd29, %rd25, %rd27;
	ld.global.nc.f32 	%f14, [%rd29];
	mul.f32 	%f15, %f14, %f14;
	fma.rn.f32 	%f16, %f13, %f13, %f15;
	add.s64 	%rd30, %rd24, %rd27;
	ld.global.nc.f32 	%f17, [%rd30];
	fma.rn.f32 	%f18, %f17, %f17, %f16;
	cvt.f64.f32	%fd3, %f18;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64	%f19, %fd4;
	add.s64 	%rd31, %rd23, %rd27;
	mul.f32 	%f20, %f14, %f17;
	fma.rn.f32 	%f21, %f13, %f14, %f20;
	fma.rn.f32 	%f22, %f13, %f17, %f21;
	fma.rn.f32 	%f23, %f33, %f22, %f19;
	add.s64 	%rd32, %rd22, %rd27;
	ld.global.nc.f32 	%f24, [%rd32];
	add.s64 	%rd33, %rd21, %rd27;
	ld.global.nc.f32 	%f25, [%rd33];
	mul.f32 	%f26, %f25, %f25;
	fma.rn.f32 	%f27, %f24, %f24, %f26;
	add.s64 	%rd34, %rd20, %rd27;
	ld.global.nc.f32 	%f28, [%rd34];
	fma.rn.f32 	%f29, %f28, %f28, %f27;
	add.f32 	%f30, %f34, %f34;
	fma.rn.f32 	%f31, %f30, %f29, %f23;
	st.global.f32 	[%rd31], %f31;

BB0_8:
	ret;
}


`
   ElsticEnergy_ptx_50 = `
.version 6.3
.target sm_50
.address_size 64

	// .globl	ElsticEnergy

.visible .entry ElsticEnergy(
	.param .u64 ElsticEnergy_param_0,
	.param .u64 ElsticEnergy_param_1,
	.param .u64 ElsticEnergy_param_2,
	.param .u64 ElsticEnergy_param_3,
	.param .u64 ElsticEnergy_param_4,
	.param .u64 ElsticEnergy_param_5,
	.param .u64 ElsticEnergy_param_6,
	.param .u32 ElsticEnergy_param_7,
	.param .u32 ElsticEnergy_param_8,
	.param .u32 ElsticEnergy_param_9,
	.param .u64 ElsticEnergy_param_10,
	.param .f32 ElsticEnergy_param_11,
	.param .u64 ElsticEnergy_param_12,
	.param .f32 ElsticEnergy_param_13,
	.param .u64 ElsticEnergy_param_14,
	.param .f32 ElsticEnergy_param_15
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<35>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<35>;


	ld.param.u64 	%rd1, [ElsticEnergy_param_0];
	ld.param.u64 	%rd2, [ElsticEnergy_param_1];
	ld.param.u64 	%rd3, [ElsticEnergy_param_2];
	ld.param.u64 	%rd4, [ElsticEnergy_param_3];
	ld.param.u64 	%rd5, [ElsticEnergy_param_4];
	ld.param.u64 	%rd6, [ElsticEnergy_param_5];
	ld.param.u64 	%rd7, [ElsticEnergy_param_6];
	ld.param.u32 	%r5, [ElsticEnergy_param_7];
	ld.param.u32 	%r6, [ElsticEnergy_param_8];
	ld.param.u32 	%r7, [ElsticEnergy_param_9];
	ld.param.u64 	%rd8, [ElsticEnergy_param_10];
	ld.param.f32 	%f32, [ElsticEnergy_param_11];
	ld.param.u64 	%rd9, [ElsticEnergy_param_12];
	ld.param.f32 	%f33, [ElsticEnergy_param_13];
	ld.param.u64 	%rd10, [ElsticEnergy_param_14];
	ld.param.f32 	%f34, [ElsticEnergy_param_15];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r14, %r15, %r16;
	setp.ge.s32	%p1, %r2, %r6;
	setp.ge.s32	%p2, %r1, %r5;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_8;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64	%p6, %rd8, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd11, %rd8;
	mul.wide.s32 	%rd12, %r4, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.nc.f32 	%f10, [%rd13];
	mul.f32 	%f32, %f10, %f32;

BB0_3:
	setp.eq.s64	%p7, %rd9, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd14, %rd9;
	mul.wide.s32 	%rd15, %r4, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f11, [%rd16];
	mul.f32 	%f33, %f11, %f33;

BB0_5:
	setp.eq.s64	%p8, %rd10, 0;
	@%p8 bra 	BB0_7;

	cvta.to.global.u64 	%rd17, %rd10;
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.nc.f32 	%f12, [%rd19];
	mul.f32 	%f34, %f12, %f34;

BB0_7:
	cvta.to.global.u64 	%rd20, %rd7;
	cvta.to.global.u64 	%rd21, %rd6;
	cvta.to.global.u64 	%rd22, %rd5;
	cvta.to.global.u64 	%rd23, %rd1;
	cvta.to.global.u64 	%rd24, %rd4;
	cvta.to.global.u64 	%rd25, %rd3;
	cvta.to.global.u64 	%rd26, %rd2;
	cvt.f64.f32	%fd1, %f32;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	mul.wide.s32 	%rd27, %r4, 4;
	add.s64 	%rd28, %rd26, %rd27;
	ld.global.nc.f32 	%f13, [%rd28];
	add.s64 	%rd29, %rd25, %rd27;
	ld.global.nc.f32 	%f14, [%rd29];
	mul.f32 	%f15, %f14, %f14;
	fma.rn.f32 	%f16, %f13, %f13, %f15;
	add.s64 	%rd30, %rd24, %rd27;
	ld.global.nc.f32 	%f17, [%rd30];
	fma.rn.f32 	%f18, %f17, %f17, %f16;
	cvt.f64.f32	%fd3, %f18;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64	%f19, %fd4;
	add.s64 	%rd31, %rd23, %rd27;
	mul.f32 	%f20, %f14, %f17;
	fma.rn.f32 	%f21, %f13, %f14, %f20;
	fma.rn.f32 	%f22, %f13, %f17, %f21;
	fma.rn.f32 	%f23, %f33, %f22, %f19;
	add.s64 	%rd32, %rd22, %rd27;
	ld.global.nc.f32 	%f24, [%rd32];
	add.s64 	%rd33, %rd21, %rd27;
	ld.global.nc.f32 	%f25, [%rd33];
	mul.f32 	%f26, %f25, %f25;
	fma.rn.f32 	%f27, %f24, %f24, %f26;
	add.s64 	%rd34, %rd20, %rd27;
	ld.global.nc.f32 	%f28, [%rd34];
	fma.rn.f32 	%f29, %f28, %f28, %f27;
	add.f32 	%f30, %f34, %f34;
	fma.rn.f32 	%f31, %f30, %f29, %f23;
	st.global.f32 	[%rd31], %f31;

BB0_8:
	ret;
}


`
   ElsticEnergy_ptx_52 = `
.version 6.3
.target sm_52
.address_size 64

	// .globl	ElsticEnergy

.visible .entry ElsticEnergy(
	.param .u64 ElsticEnergy_param_0,
	.param .u64 ElsticEnergy_param_1,
	.param .u64 ElsticEnergy_param_2,
	.param .u64 ElsticEnergy_param_3,
	.param .u64 ElsticEnergy_param_4,
	.param .u64 ElsticEnergy_param_5,
	.param .u64 ElsticEnergy_param_6,
	.param .u32 ElsticEnergy_param_7,
	.param .u32 ElsticEnergy_param_8,
	.param .u32 ElsticEnergy_param_9,
	.param .u64 ElsticEnergy_param_10,
	.param .f32 ElsticEnergy_param_11,
	.param .u64 ElsticEnergy_param_12,
	.param .f32 ElsticEnergy_param_13,
	.param .u64 ElsticEnergy_param_14,
	.param .f32 ElsticEnergy_param_15
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<35>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<35>;


	ld.param.u64 	%rd1, [ElsticEnergy_param_0];
	ld.param.u64 	%rd2, [ElsticEnergy_param_1];
	ld.param.u64 	%rd3, [ElsticEnergy_param_2];
	ld.param.u64 	%rd4, [ElsticEnergy_param_3];
	ld.param.u64 	%rd5, [ElsticEnergy_param_4];
	ld.param.u64 	%rd6, [ElsticEnergy_param_5];
	ld.param.u64 	%rd7, [ElsticEnergy_param_6];
	ld.param.u32 	%r5, [ElsticEnergy_param_7];
	ld.param.u32 	%r6, [ElsticEnergy_param_8];
	ld.param.u32 	%r7, [ElsticEnergy_param_9];
	ld.param.u64 	%rd8, [ElsticEnergy_param_10];
	ld.param.f32 	%f32, [ElsticEnergy_param_11];
	ld.param.u64 	%rd9, [ElsticEnergy_param_12];
	ld.param.f32 	%f33, [ElsticEnergy_param_13];
	ld.param.u64 	%rd10, [ElsticEnergy_param_14];
	ld.param.f32 	%f34, [ElsticEnergy_param_15];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r14, %r15, %r16;
	setp.ge.s32	%p1, %r2, %r6;
	setp.ge.s32	%p2, %r1, %r5;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_8;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64	%p6, %rd8, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd11, %rd8;
	mul.wide.s32 	%rd12, %r4, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.nc.f32 	%f10, [%rd13];
	mul.f32 	%f32, %f10, %f32;

BB0_3:
	setp.eq.s64	%p7, %rd9, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd14, %rd9;
	mul.wide.s32 	%rd15, %r4, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f11, [%rd16];
	mul.f32 	%f33, %f11, %f33;

BB0_5:
	setp.eq.s64	%p8, %rd10, 0;
	@%p8 bra 	BB0_7;

	cvta.to.global.u64 	%rd17, %rd10;
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.nc.f32 	%f12, [%rd19];
	mul.f32 	%f34, %f12, %f34;

BB0_7:
	cvta.to.global.u64 	%rd20, %rd7;
	cvta.to.global.u64 	%rd21, %rd6;
	cvta.to.global.u64 	%rd22, %rd5;
	cvta.to.global.u64 	%rd23, %rd1;
	cvta.to.global.u64 	%rd24, %rd4;
	cvta.to.global.u64 	%rd25, %rd3;
	cvta.to.global.u64 	%rd26, %rd2;
	cvt.f64.f32	%fd1, %f32;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	mul.wide.s32 	%rd27, %r4, 4;
	add.s64 	%rd28, %rd26, %rd27;
	ld.global.nc.f32 	%f13, [%rd28];
	add.s64 	%rd29, %rd25, %rd27;
	ld.global.nc.f32 	%f14, [%rd29];
	mul.f32 	%f15, %f14, %f14;
	fma.rn.f32 	%f16, %f13, %f13, %f15;
	add.s64 	%rd30, %rd24, %rd27;
	ld.global.nc.f32 	%f17, [%rd30];
	fma.rn.f32 	%f18, %f17, %f17, %f16;
	cvt.f64.f32	%fd3, %f18;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64	%f19, %fd4;
	add.s64 	%rd31, %rd23, %rd27;
	mul.f32 	%f20, %f14, %f17;
	fma.rn.f32 	%f21, %f13, %f14, %f20;
	fma.rn.f32 	%f22, %f13, %f17, %f21;
	fma.rn.f32 	%f23, %f33, %f22, %f19;
	add.s64 	%rd32, %rd22, %rd27;
	ld.global.nc.f32 	%f24, [%rd32];
	add.s64 	%rd33, %rd21, %rd27;
	ld.global.nc.f32 	%f25, [%rd33];
	mul.f32 	%f26, %f25, %f25;
	fma.rn.f32 	%f27, %f24, %f24, %f26;
	add.s64 	%rd34, %rd20, %rd27;
	ld.global.nc.f32 	%f28, [%rd34];
	fma.rn.f32 	%f29, %f28, %f28, %f27;
	add.f32 	%f30, %f34, %f34;
	fma.rn.f32 	%f31, %f30, %f29, %f23;
	st.global.f32 	[%rd31], %f31;

BB0_8:
	ret;
}


`
   ElsticEnergy_ptx_53 = `
.version 6.3
.target sm_53
.address_size 64

	// .globl	ElsticEnergy

.visible .entry ElsticEnergy(
	.param .u64 ElsticEnergy_param_0,
	.param .u64 ElsticEnergy_param_1,
	.param .u64 ElsticEnergy_param_2,
	.param .u64 ElsticEnergy_param_3,
	.param .u64 ElsticEnergy_param_4,
	.param .u64 ElsticEnergy_param_5,
	.param .u64 ElsticEnergy_param_6,
	.param .u32 ElsticEnergy_param_7,
	.param .u32 ElsticEnergy_param_8,
	.param .u32 ElsticEnergy_param_9,
	.param .u64 ElsticEnergy_param_10,
	.param .f32 ElsticEnergy_param_11,
	.param .u64 ElsticEnergy_param_12,
	.param .f32 ElsticEnergy_param_13,
	.param .u64 ElsticEnergy_param_14,
	.param .f32 ElsticEnergy_param_15
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<35>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<35>;


	ld.param.u64 	%rd1, [ElsticEnergy_param_0];
	ld.param.u64 	%rd2, [ElsticEnergy_param_1];
	ld.param.u64 	%rd3, [ElsticEnergy_param_2];
	ld.param.u64 	%rd4, [ElsticEnergy_param_3];
	ld.param.u64 	%rd5, [ElsticEnergy_param_4];
	ld.param.u64 	%rd6, [ElsticEnergy_param_5];
	ld.param.u64 	%rd7, [ElsticEnergy_param_6];
	ld.param.u32 	%r5, [ElsticEnergy_param_7];
	ld.param.u32 	%r6, [ElsticEnergy_param_8];
	ld.param.u32 	%r7, [ElsticEnergy_param_9];
	ld.param.u64 	%rd8, [ElsticEnergy_param_10];
	ld.param.f32 	%f32, [ElsticEnergy_param_11];
	ld.param.u64 	%rd9, [ElsticEnergy_param_12];
	ld.param.f32 	%f33, [ElsticEnergy_param_13];
	ld.param.u64 	%rd10, [ElsticEnergy_param_14];
	ld.param.f32 	%f34, [ElsticEnergy_param_15];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r14, %r15, %r16;
	setp.ge.s32	%p1, %r2, %r6;
	setp.ge.s32	%p2, %r1, %r5;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_8;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64	%p6, %rd8, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd11, %rd8;
	mul.wide.s32 	%rd12, %r4, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.nc.f32 	%f10, [%rd13];
	mul.f32 	%f32, %f10, %f32;

BB0_3:
	setp.eq.s64	%p7, %rd9, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd14, %rd9;
	mul.wide.s32 	%rd15, %r4, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f11, [%rd16];
	mul.f32 	%f33, %f11, %f33;

BB0_5:
	setp.eq.s64	%p8, %rd10, 0;
	@%p8 bra 	BB0_7;

	cvta.to.global.u64 	%rd17, %rd10;
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.nc.f32 	%f12, [%rd19];
	mul.f32 	%f34, %f12, %f34;

BB0_7:
	cvta.to.global.u64 	%rd20, %rd7;
	cvta.to.global.u64 	%rd21, %rd6;
	cvta.to.global.u64 	%rd22, %rd5;
	cvta.to.global.u64 	%rd23, %rd1;
	cvta.to.global.u64 	%rd24, %rd4;
	cvta.to.global.u64 	%rd25, %rd3;
	cvta.to.global.u64 	%rd26, %rd2;
	cvt.f64.f32	%fd1, %f32;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	mul.wide.s32 	%rd27, %r4, 4;
	add.s64 	%rd28, %rd26, %rd27;
	ld.global.nc.f32 	%f13, [%rd28];
	add.s64 	%rd29, %rd25, %rd27;
	ld.global.nc.f32 	%f14, [%rd29];
	mul.f32 	%f15, %f14, %f14;
	fma.rn.f32 	%f16, %f13, %f13, %f15;
	add.s64 	%rd30, %rd24, %rd27;
	ld.global.nc.f32 	%f17, [%rd30];
	fma.rn.f32 	%f18, %f17, %f17, %f16;
	cvt.f64.f32	%fd3, %f18;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64	%f19, %fd4;
	add.s64 	%rd31, %rd23, %rd27;
	mul.f32 	%f20, %f14, %f17;
	fma.rn.f32 	%f21, %f13, %f14, %f20;
	fma.rn.f32 	%f22, %f13, %f17, %f21;
	fma.rn.f32 	%f23, %f33, %f22, %f19;
	add.s64 	%rd32, %rd22, %rd27;
	ld.global.nc.f32 	%f24, [%rd32];
	add.s64 	%rd33, %rd21, %rd27;
	ld.global.nc.f32 	%f25, [%rd33];
	mul.f32 	%f26, %f25, %f25;
	fma.rn.f32 	%f27, %f24, %f24, %f26;
	add.s64 	%rd34, %rd20, %rd27;
	ld.global.nc.f32 	%f28, [%rd34];
	fma.rn.f32 	%f29, %f28, %f28, %f27;
	add.f32 	%f30, %f34, %f34;
	fma.rn.f32 	%f31, %f30, %f29, %f23;
	st.global.f32 	[%rd31], %f31;

BB0_8:
	ret;
}


`
   ElsticEnergy_ptx_60 = `
.version 6.3
.target sm_60
.address_size 64

	// .globl	ElsticEnergy

.visible .entry ElsticEnergy(
	.param .u64 ElsticEnergy_param_0,
	.param .u64 ElsticEnergy_param_1,
	.param .u64 ElsticEnergy_param_2,
	.param .u64 ElsticEnergy_param_3,
	.param .u64 ElsticEnergy_param_4,
	.param .u64 ElsticEnergy_param_5,
	.param .u64 ElsticEnergy_param_6,
	.param .u32 ElsticEnergy_param_7,
	.param .u32 ElsticEnergy_param_8,
	.param .u32 ElsticEnergy_param_9,
	.param .u64 ElsticEnergy_param_10,
	.param .f32 ElsticEnergy_param_11,
	.param .u64 ElsticEnergy_param_12,
	.param .f32 ElsticEnergy_param_13,
	.param .u64 ElsticEnergy_param_14,
	.param .f32 ElsticEnergy_param_15
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<35>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<35>;


	ld.param.u64 	%rd1, [ElsticEnergy_param_0];
	ld.param.u64 	%rd2, [ElsticEnergy_param_1];
	ld.param.u64 	%rd3, [ElsticEnergy_param_2];
	ld.param.u64 	%rd4, [ElsticEnergy_param_3];
	ld.param.u64 	%rd5, [ElsticEnergy_param_4];
	ld.param.u64 	%rd6, [ElsticEnergy_param_5];
	ld.param.u64 	%rd7, [ElsticEnergy_param_6];
	ld.param.u32 	%r5, [ElsticEnergy_param_7];
	ld.param.u32 	%r6, [ElsticEnergy_param_8];
	ld.param.u32 	%r7, [ElsticEnergy_param_9];
	ld.param.u64 	%rd8, [ElsticEnergy_param_10];
	ld.param.f32 	%f32, [ElsticEnergy_param_11];
	ld.param.u64 	%rd9, [ElsticEnergy_param_12];
	ld.param.f32 	%f33, [ElsticEnergy_param_13];
	ld.param.u64 	%rd10, [ElsticEnergy_param_14];
	ld.param.f32 	%f34, [ElsticEnergy_param_15];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r14, %r15, %r16;
	setp.ge.s32	%p1, %r2, %r6;
	setp.ge.s32	%p2, %r1, %r5;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_8;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64	%p6, %rd8, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd11, %rd8;
	mul.wide.s32 	%rd12, %r4, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.nc.f32 	%f10, [%rd13];
	mul.f32 	%f32, %f10, %f32;

BB0_3:
	setp.eq.s64	%p7, %rd9, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd14, %rd9;
	mul.wide.s32 	%rd15, %r4, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f11, [%rd16];
	mul.f32 	%f33, %f11, %f33;

BB0_5:
	setp.eq.s64	%p8, %rd10, 0;
	@%p8 bra 	BB0_7;

	cvta.to.global.u64 	%rd17, %rd10;
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.nc.f32 	%f12, [%rd19];
	mul.f32 	%f34, %f12, %f34;

BB0_7:
	cvta.to.global.u64 	%rd20, %rd7;
	cvta.to.global.u64 	%rd21, %rd6;
	cvta.to.global.u64 	%rd22, %rd5;
	cvta.to.global.u64 	%rd23, %rd1;
	cvta.to.global.u64 	%rd24, %rd4;
	cvta.to.global.u64 	%rd25, %rd3;
	cvta.to.global.u64 	%rd26, %rd2;
	cvt.f64.f32	%fd1, %f32;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	mul.wide.s32 	%rd27, %r4, 4;
	add.s64 	%rd28, %rd26, %rd27;
	ld.global.nc.f32 	%f13, [%rd28];
	add.s64 	%rd29, %rd25, %rd27;
	ld.global.nc.f32 	%f14, [%rd29];
	mul.f32 	%f15, %f14, %f14;
	fma.rn.f32 	%f16, %f13, %f13, %f15;
	add.s64 	%rd30, %rd24, %rd27;
	ld.global.nc.f32 	%f17, [%rd30];
	fma.rn.f32 	%f18, %f17, %f17, %f16;
	cvt.f64.f32	%fd3, %f18;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64	%f19, %fd4;
	add.s64 	%rd31, %rd23, %rd27;
	mul.f32 	%f20, %f14, %f17;
	fma.rn.f32 	%f21, %f13, %f14, %f20;
	fma.rn.f32 	%f22, %f13, %f17, %f21;
	fma.rn.f32 	%f23, %f33, %f22, %f19;
	add.s64 	%rd32, %rd22, %rd27;
	ld.global.nc.f32 	%f24, [%rd32];
	add.s64 	%rd33, %rd21, %rd27;
	ld.global.nc.f32 	%f25, [%rd33];
	mul.f32 	%f26, %f25, %f25;
	fma.rn.f32 	%f27, %f24, %f24, %f26;
	add.s64 	%rd34, %rd20, %rd27;
	ld.global.nc.f32 	%f28, [%rd34];
	fma.rn.f32 	%f29, %f28, %f28, %f27;
	add.f32 	%f30, %f34, %f34;
	fma.rn.f32 	%f31, %f30, %f29, %f23;
	st.global.f32 	[%rd31], %f31;

BB0_8:
	ret;
}


`
   ElsticEnergy_ptx_61 = `
.version 6.3
.target sm_61
.address_size 64

	// .globl	ElsticEnergy

.visible .entry ElsticEnergy(
	.param .u64 ElsticEnergy_param_0,
	.param .u64 ElsticEnergy_param_1,
	.param .u64 ElsticEnergy_param_2,
	.param .u64 ElsticEnergy_param_3,
	.param .u64 ElsticEnergy_param_4,
	.param .u64 ElsticEnergy_param_5,
	.param .u64 ElsticEnergy_param_6,
	.param .u32 ElsticEnergy_param_7,
	.param .u32 ElsticEnergy_param_8,
	.param .u32 ElsticEnergy_param_9,
	.param .u64 ElsticEnergy_param_10,
	.param .f32 ElsticEnergy_param_11,
	.param .u64 ElsticEnergy_param_12,
	.param .f32 ElsticEnergy_param_13,
	.param .u64 ElsticEnergy_param_14,
	.param .f32 ElsticEnergy_param_15
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<35>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<35>;


	ld.param.u64 	%rd1, [ElsticEnergy_param_0];
	ld.param.u64 	%rd2, [ElsticEnergy_param_1];
	ld.param.u64 	%rd3, [ElsticEnergy_param_2];
	ld.param.u64 	%rd4, [ElsticEnergy_param_3];
	ld.param.u64 	%rd5, [ElsticEnergy_param_4];
	ld.param.u64 	%rd6, [ElsticEnergy_param_5];
	ld.param.u64 	%rd7, [ElsticEnergy_param_6];
	ld.param.u32 	%r5, [ElsticEnergy_param_7];
	ld.param.u32 	%r6, [ElsticEnergy_param_8];
	ld.param.u32 	%r7, [ElsticEnergy_param_9];
	ld.param.u64 	%rd8, [ElsticEnergy_param_10];
	ld.param.f32 	%f32, [ElsticEnergy_param_11];
	ld.param.u64 	%rd9, [ElsticEnergy_param_12];
	ld.param.f32 	%f33, [ElsticEnergy_param_13];
	ld.param.u64 	%rd10, [ElsticEnergy_param_14];
	ld.param.f32 	%f34, [ElsticEnergy_param_15];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r14, %r15, %r16;
	setp.ge.s32	%p1, %r2, %r6;
	setp.ge.s32	%p2, %r1, %r5;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_8;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64	%p6, %rd8, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd11, %rd8;
	mul.wide.s32 	%rd12, %r4, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.nc.f32 	%f10, [%rd13];
	mul.f32 	%f32, %f10, %f32;

BB0_3:
	setp.eq.s64	%p7, %rd9, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd14, %rd9;
	mul.wide.s32 	%rd15, %r4, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f11, [%rd16];
	mul.f32 	%f33, %f11, %f33;

BB0_5:
	setp.eq.s64	%p8, %rd10, 0;
	@%p8 bra 	BB0_7;

	cvta.to.global.u64 	%rd17, %rd10;
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.nc.f32 	%f12, [%rd19];
	mul.f32 	%f34, %f12, %f34;

BB0_7:
	cvta.to.global.u64 	%rd20, %rd7;
	cvta.to.global.u64 	%rd21, %rd6;
	cvta.to.global.u64 	%rd22, %rd5;
	cvta.to.global.u64 	%rd23, %rd1;
	cvta.to.global.u64 	%rd24, %rd4;
	cvta.to.global.u64 	%rd25, %rd3;
	cvta.to.global.u64 	%rd26, %rd2;
	cvt.f64.f32	%fd1, %f32;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	mul.wide.s32 	%rd27, %r4, 4;
	add.s64 	%rd28, %rd26, %rd27;
	ld.global.nc.f32 	%f13, [%rd28];
	add.s64 	%rd29, %rd25, %rd27;
	ld.global.nc.f32 	%f14, [%rd29];
	mul.f32 	%f15, %f14, %f14;
	fma.rn.f32 	%f16, %f13, %f13, %f15;
	add.s64 	%rd30, %rd24, %rd27;
	ld.global.nc.f32 	%f17, [%rd30];
	fma.rn.f32 	%f18, %f17, %f17, %f16;
	cvt.f64.f32	%fd3, %f18;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64	%f19, %fd4;
	add.s64 	%rd31, %rd23, %rd27;
	mul.f32 	%f20, %f14, %f17;
	fma.rn.f32 	%f21, %f13, %f14, %f20;
	fma.rn.f32 	%f22, %f13, %f17, %f21;
	fma.rn.f32 	%f23, %f33, %f22, %f19;
	add.s64 	%rd32, %rd22, %rd27;
	ld.global.nc.f32 	%f24, [%rd32];
	add.s64 	%rd33, %rd21, %rd27;
	ld.global.nc.f32 	%f25, [%rd33];
	mul.f32 	%f26, %f25, %f25;
	fma.rn.f32 	%f27, %f24, %f24, %f26;
	add.s64 	%rd34, %rd20, %rd27;
	ld.global.nc.f32 	%f28, [%rd34];
	fma.rn.f32 	%f29, %f28, %f28, %f27;
	add.f32 	%f30, %f34, %f34;
	fma.rn.f32 	%f31, %f30, %f29, %f23;
	st.global.f32 	[%rd31], %f31;

BB0_8:
	ret;
}


`
   ElsticEnergy_ptx_70 = `
.version 6.3
.target sm_70
.address_size 64

	// .globl	ElsticEnergy

.visible .entry ElsticEnergy(
	.param .u64 ElsticEnergy_param_0,
	.param .u64 ElsticEnergy_param_1,
	.param .u64 ElsticEnergy_param_2,
	.param .u64 ElsticEnergy_param_3,
	.param .u64 ElsticEnergy_param_4,
	.param .u64 ElsticEnergy_param_5,
	.param .u64 ElsticEnergy_param_6,
	.param .u32 ElsticEnergy_param_7,
	.param .u32 ElsticEnergy_param_8,
	.param .u32 ElsticEnergy_param_9,
	.param .u64 ElsticEnergy_param_10,
	.param .f32 ElsticEnergy_param_11,
	.param .u64 ElsticEnergy_param_12,
	.param .f32 ElsticEnergy_param_13,
	.param .u64 ElsticEnergy_param_14,
	.param .f32 ElsticEnergy_param_15
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<35>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<35>;


	ld.param.u64 	%rd1, [ElsticEnergy_param_0];
	ld.param.u64 	%rd2, [ElsticEnergy_param_1];
	ld.param.u64 	%rd3, [ElsticEnergy_param_2];
	ld.param.u64 	%rd4, [ElsticEnergy_param_3];
	ld.param.u64 	%rd5, [ElsticEnergy_param_4];
	ld.param.u64 	%rd6, [ElsticEnergy_param_5];
	ld.param.u64 	%rd7, [ElsticEnergy_param_6];
	ld.param.u32 	%r5, [ElsticEnergy_param_7];
	ld.param.u32 	%r6, [ElsticEnergy_param_8];
	ld.param.u32 	%r7, [ElsticEnergy_param_9];
	ld.param.u64 	%rd8, [ElsticEnergy_param_10];
	ld.param.f32 	%f32, [ElsticEnergy_param_11];
	ld.param.u64 	%rd9, [ElsticEnergy_param_12];
	ld.param.f32 	%f33, [ElsticEnergy_param_13];
	ld.param.u64 	%rd10, [ElsticEnergy_param_14];
	ld.param.f32 	%f34, [ElsticEnergy_param_15];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r14, %r15, %r16;
	setp.ge.s32	%p1, %r2, %r6;
	setp.ge.s32	%p2, %r1, %r5;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_8;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64	%p6, %rd8, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd11, %rd8;
	mul.wide.s32 	%rd12, %r4, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.nc.f32 	%f10, [%rd13];
	mul.f32 	%f32, %f10, %f32;

BB0_3:
	setp.eq.s64	%p7, %rd9, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd14, %rd9;
	mul.wide.s32 	%rd15, %r4, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f11, [%rd16];
	mul.f32 	%f33, %f11, %f33;

BB0_5:
	setp.eq.s64	%p8, %rd10, 0;
	@%p8 bra 	BB0_7;

	cvta.to.global.u64 	%rd17, %rd10;
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.nc.f32 	%f12, [%rd19];
	mul.f32 	%f34, %f12, %f34;

BB0_7:
	cvta.to.global.u64 	%rd20, %rd7;
	cvta.to.global.u64 	%rd21, %rd6;
	cvta.to.global.u64 	%rd22, %rd5;
	cvta.to.global.u64 	%rd23, %rd1;
	cvta.to.global.u64 	%rd24, %rd4;
	cvta.to.global.u64 	%rd25, %rd3;
	cvta.to.global.u64 	%rd26, %rd2;
	cvt.f64.f32	%fd1, %f32;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	mul.wide.s32 	%rd27, %r4, 4;
	add.s64 	%rd28, %rd26, %rd27;
	ld.global.nc.f32 	%f13, [%rd28];
	add.s64 	%rd29, %rd25, %rd27;
	ld.global.nc.f32 	%f14, [%rd29];
	mul.f32 	%f15, %f14, %f14;
	fma.rn.f32 	%f16, %f13, %f13, %f15;
	add.s64 	%rd30, %rd24, %rd27;
	ld.global.nc.f32 	%f17, [%rd30];
	fma.rn.f32 	%f18, %f17, %f17, %f16;
	cvt.f64.f32	%fd3, %f18;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64	%f19, %fd4;
	add.s64 	%rd31, %rd23, %rd27;
	mul.f32 	%f20, %f14, %f17;
	fma.rn.f32 	%f21, %f13, %f14, %f20;
	fma.rn.f32 	%f22, %f13, %f17, %f21;
	fma.rn.f32 	%f23, %f33, %f22, %f19;
	add.s64 	%rd32, %rd22, %rd27;
	ld.global.nc.f32 	%f24, [%rd32];
	add.s64 	%rd33, %rd21, %rd27;
	ld.global.nc.f32 	%f25, [%rd33];
	mul.f32 	%f26, %f25, %f25;
	fma.rn.f32 	%f27, %f24, %f24, %f26;
	add.s64 	%rd34, %rd20, %rd27;
	ld.global.nc.f32 	%f28, [%rd34];
	fma.rn.f32 	%f29, %f28, %f28, %f27;
	add.f32 	%f30, %f34, %f34;
	fma.rn.f32 	%f31, %f30, %f29, %f23;
	st.global.f32 	[%rd31], %f31;

BB0_8:
	ret;
}


`
   ElsticEnergy_ptx_75 = `
.version 6.3
.target sm_75
.address_size 64

	// .globl	ElsticEnergy

.visible .entry ElsticEnergy(
	.param .u64 ElsticEnergy_param_0,
	.param .u64 ElsticEnergy_param_1,
	.param .u64 ElsticEnergy_param_2,
	.param .u64 ElsticEnergy_param_3,
	.param .u64 ElsticEnergy_param_4,
	.param .u64 ElsticEnergy_param_5,
	.param .u64 ElsticEnergy_param_6,
	.param .u32 ElsticEnergy_param_7,
	.param .u32 ElsticEnergy_param_8,
	.param .u32 ElsticEnergy_param_9,
	.param .u64 ElsticEnergy_param_10,
	.param .f32 ElsticEnergy_param_11,
	.param .u64 ElsticEnergy_param_12,
	.param .f32 ElsticEnergy_param_13,
	.param .u64 ElsticEnergy_param_14,
	.param .f32 ElsticEnergy_param_15
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<35>;
	.reg .b32 	%r<18>;
	.reg .f64 	%fd<5>;
	.reg .b64 	%rd<35>;


	ld.param.u64 	%rd1, [ElsticEnergy_param_0];
	ld.param.u64 	%rd2, [ElsticEnergy_param_1];
	ld.param.u64 	%rd3, [ElsticEnergy_param_2];
	ld.param.u64 	%rd4, [ElsticEnergy_param_3];
	ld.param.u64 	%rd5, [ElsticEnergy_param_4];
	ld.param.u64 	%rd6, [ElsticEnergy_param_5];
	ld.param.u64 	%rd7, [ElsticEnergy_param_6];
	ld.param.u32 	%r5, [ElsticEnergy_param_7];
	ld.param.u32 	%r6, [ElsticEnergy_param_8];
	ld.param.u32 	%r7, [ElsticEnergy_param_9];
	ld.param.u64 	%rd8, [ElsticEnergy_param_10];
	ld.param.f32 	%f32, [ElsticEnergy_param_11];
	ld.param.u64 	%rd9, [ElsticEnergy_param_12];
	ld.param.f32 	%f33, [ElsticEnergy_param_13];
	ld.param.u64 	%rd10, [ElsticEnergy_param_14];
	ld.param.f32 	%f34, [ElsticEnergy_param_15];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r8, %r9, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r11, %r12, %r13;
	mov.u32 	%r14, %ntid.z;
	mov.u32 	%r15, %ctaid.z;
	mov.u32 	%r16, %tid.z;
	mad.lo.s32 	%r3, %r14, %r15, %r16;
	setp.ge.s32	%p1, %r2, %r6;
	setp.ge.s32	%p2, %r1, %r5;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r7;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_8;

	mad.lo.s32 	%r17, %r3, %r6, %r2;
	mad.lo.s32 	%r4, %r17, %r5, %r1;
	setp.eq.s64	%p6, %rd8, 0;
	@%p6 bra 	BB0_3;

	cvta.to.global.u64 	%rd11, %rd8;
	mul.wide.s32 	%rd12, %r4, 4;
	add.s64 	%rd13, %rd11, %rd12;
	ld.global.nc.f32 	%f10, [%rd13];
	mul.f32 	%f32, %f10, %f32;

BB0_3:
	setp.eq.s64	%p7, %rd9, 0;
	@%p7 bra 	BB0_5;

	cvta.to.global.u64 	%rd14, %rd9;
	mul.wide.s32 	%rd15, %r4, 4;
	add.s64 	%rd16, %rd14, %rd15;
	ld.global.nc.f32 	%f11, [%rd16];
	mul.f32 	%f33, %f11, %f33;

BB0_5:
	setp.eq.s64	%p8, %rd10, 0;
	@%p8 bra 	BB0_7;

	cvta.to.global.u64 	%rd17, %rd10;
	mul.wide.s32 	%rd18, %r4, 4;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.nc.f32 	%f12, [%rd19];
	mul.f32 	%f34, %f12, %f34;

BB0_7:
	cvta.to.global.u64 	%rd20, %rd7;
	cvta.to.global.u64 	%rd21, %rd6;
	cvta.to.global.u64 	%rd22, %rd5;
	cvta.to.global.u64 	%rd23, %rd1;
	cvta.to.global.u64 	%rd24, %rd4;
	cvta.to.global.u64 	%rd25, %rd3;
	cvta.to.global.u64 	%rd26, %rd2;
	cvt.f64.f32	%fd1, %f32;
	mul.f64 	%fd2, %fd1, 0d3FE0000000000000;
	mul.wide.s32 	%rd27, %r4, 4;
	add.s64 	%rd28, %rd26, %rd27;
	ld.global.nc.f32 	%f13, [%rd28];
	add.s64 	%rd29, %rd25, %rd27;
	ld.global.nc.f32 	%f14, [%rd29];
	mul.f32 	%f15, %f14, %f14;
	fma.rn.f32 	%f16, %f13, %f13, %f15;
	add.s64 	%rd30, %rd24, %rd27;
	ld.global.nc.f32 	%f17, [%rd30];
	fma.rn.f32 	%f18, %f17, %f17, %f16;
	cvt.f64.f32	%fd3, %f18;
	mul.f64 	%fd4, %fd2, %fd3;
	cvt.rn.f32.f64	%f19, %fd4;
	add.s64 	%rd31, %rd23, %rd27;
	mul.f32 	%f20, %f14, %f17;
	fma.rn.f32 	%f21, %f13, %f14, %f20;
	fma.rn.f32 	%f22, %f13, %f17, %f21;
	fma.rn.f32 	%f23, %f33, %f22, %f19;
	add.s64 	%rd32, %rd22, %rd27;
	ld.global.nc.f32 	%f24, [%rd32];
	add.s64 	%rd33, %rd21, %rd27;
	ld.global.nc.f32 	%f25, [%rd33];
	mul.f32 	%f26, %f25, %f25;
	fma.rn.f32 	%f27, %f24, %f24, %f26;
	add.s64 	%rd34, %rd20, %rd27;
	ld.global.nc.f32 	%f28, [%rd34];
	fma.rn.f32 	%f29, %f28, %f28, %f27;
	add.f32 	%f30, %f34, %f34;
	fma.rn.f32 	%f31, %f30, %f29, %f23;
	st.global.f32 	[%rd31], %f31;

BB0_8:
	ret;
}


`
 )
