package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
)

// CUDA handle for addmagnetoelasticfield kernel
var addmagnetoelasticfield_code cu.Function

// Stores the arguments for addmagnetoelasticfield kernel invocation
type addmagnetoelasticfield_args_t struct{
	 arg_Bx unsafe.Pointer
	 arg_By unsafe.Pointer
	 arg_Bz unsafe.Pointer
	 arg_mx unsafe.Pointer
	 arg_my unsafe.Pointer
	 arg_mz unsafe.Pointer
	 arg_exx unsafe.Pointer
	 arg_eyy unsafe.Pointer
	 arg_ezz unsafe.Pointer
	 arg_exy unsafe.Pointer
	 arg_eyz unsafe.Pointer
	 arg_exz unsafe.Pointer
	 arg_B1_ unsafe.Pointer
	 arg_B1_mul float32
	 arg_B2_ unsafe.Pointer
	 arg_B2_mul float32
	 arg_Ms_ unsafe.Pointer
	 arg_Ms_mul float32
	 arg_N int
	 argptr [19]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for addmagnetoelasticfield kernel invocation
var addmagnetoelasticfield_args addmagnetoelasticfield_args_t

func init(){
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	 addmagnetoelasticfield_args.argptr[0] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_Bx)
	 addmagnetoelasticfield_args.argptr[1] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_By)
	 addmagnetoelasticfield_args.argptr[2] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_Bz)
	 addmagnetoelasticfield_args.argptr[3] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_mx)
	 addmagnetoelasticfield_args.argptr[4] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_my)
	 addmagnetoelasticfield_args.argptr[5] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_mz)
	 addmagnetoelasticfield_args.argptr[6] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_exx)
	 addmagnetoelasticfield_args.argptr[7] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_eyy)
	 addmagnetoelasticfield_args.argptr[8] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_ezz)
	 addmagnetoelasticfield_args.argptr[9] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_exy)
	 addmagnetoelasticfield_args.argptr[10] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_eyz)
	 addmagnetoelasticfield_args.argptr[11] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_exz)
	 addmagnetoelasticfield_args.argptr[12] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_B1_)
	 addmagnetoelasticfield_args.argptr[13] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_B1_mul)
	 addmagnetoelasticfield_args.argptr[14] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_B2_)
	 addmagnetoelasticfield_args.argptr[15] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_B2_mul)
	 addmagnetoelasticfield_args.argptr[16] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_Ms_)
	 addmagnetoelasticfield_args.argptr[17] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_Ms_mul)
	 addmagnetoelasticfield_args.argptr[18] = unsafe.Pointer(&addmagnetoelasticfield_args.arg_N)
	 }

// Wrapper for addmagnetoelasticfield CUDA kernel, asynchronous.
func k_addmagnetoelasticfield_async ( Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, exx unsafe.Pointer, eyy unsafe.Pointer, ezz unsafe.Pointer, exy unsafe.Pointer, eyz unsafe.Pointer, exz unsafe.Pointer, B1_ unsafe.Pointer, B1_mul float32, B2_ unsafe.Pointer, B2_mul float32, Ms_ unsafe.Pointer, Ms_mul float32, N int,  cfg *config) {
	if Synchronous{ // debug
		Sync()
		timer.Start("addmagnetoelasticfield")
	}

	addmagnetoelasticfield_args.Lock()
	defer addmagnetoelasticfield_args.Unlock()

	if addmagnetoelasticfield_code == 0{
		addmagnetoelasticfield_code = fatbinLoad(addmagnetoelasticfield_map, "addmagnetoelasticfield")
	}

	 addmagnetoelasticfield_args.arg_Bx = Bx
	 addmagnetoelasticfield_args.arg_By = By
	 addmagnetoelasticfield_args.arg_Bz = Bz
	 addmagnetoelasticfield_args.arg_mx = mx
	 addmagnetoelasticfield_args.arg_my = my
	 addmagnetoelasticfield_args.arg_mz = mz
	 addmagnetoelasticfield_args.arg_exx = exx
	 addmagnetoelasticfield_args.arg_eyy = eyy
	 addmagnetoelasticfield_args.arg_ezz = ezz
	 addmagnetoelasticfield_args.arg_exy = exy
	 addmagnetoelasticfield_args.arg_eyz = eyz
	 addmagnetoelasticfield_args.arg_exz = exz
	 addmagnetoelasticfield_args.arg_B1_ = B1_
	 addmagnetoelasticfield_args.arg_B1_mul = B1_mul
	 addmagnetoelasticfield_args.arg_B2_ = B2_
	 addmagnetoelasticfield_args.arg_B2_mul = B2_mul
	 addmagnetoelasticfield_args.arg_Ms_ = Ms_
	 addmagnetoelasticfield_args.arg_Ms_mul = Ms_mul
	 addmagnetoelasticfield_args.arg_N = N
	

	args := addmagnetoelasticfield_args.argptr[:]
	cu.LaunchKernel(addmagnetoelasticfield_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous{ // debug
		Sync()
		timer.Stop("addmagnetoelasticfield")
	}
}

// maps compute capability on PTX code for addmagnetoelasticfield kernel.
var addmagnetoelasticfield_map = map[int]string{ 0: "" ,
30: addmagnetoelasticfield_ptx_30 ,
35: addmagnetoelasticfield_ptx_35 ,
37: addmagnetoelasticfield_ptx_37 ,
50: addmagnetoelasticfield_ptx_50 ,
52: addmagnetoelasticfield_ptx_52 ,
53: addmagnetoelasticfield_ptx_53 ,
60: addmagnetoelasticfield_ptx_60 ,
61: addmagnetoelasticfield_ptx_61 ,
70: addmagnetoelasticfield_ptx_70 ,
75: addmagnetoelasticfield_ptx_75  }

// addmagnetoelasticfield PTX code for various compute capabilities.
const(
  addmagnetoelasticfield_ptx_30 = `
.version 6.3
.target sm_30
.address_size 64

	// .globl	addmagnetoelasticfield

.visible .entry addmagnetoelasticfield(
	.param .u64 addmagnetoelasticfield_param_0,
	.param .u64 addmagnetoelasticfield_param_1,
	.param .u64 addmagnetoelasticfield_param_2,
	.param .u64 addmagnetoelasticfield_param_3,
	.param .u64 addmagnetoelasticfield_param_4,
	.param .u64 addmagnetoelasticfield_param_5,
	.param .u64 addmagnetoelasticfield_param_6,
	.param .u64 addmagnetoelasticfield_param_7,
	.param .u64 addmagnetoelasticfield_param_8,
	.param .u64 addmagnetoelasticfield_param_9,
	.param .u64 addmagnetoelasticfield_param_10,
	.param .u64 addmagnetoelasticfield_param_11,
	.param .u64 addmagnetoelasticfield_param_12,
	.param .f32 addmagnetoelasticfield_param_13,
	.param .u64 addmagnetoelasticfield_param_14,
	.param .f32 addmagnetoelasticfield_param_15,
	.param .u64 addmagnetoelasticfield_param_16,
	.param .f32 addmagnetoelasticfield_param_17,
	.param .u32 addmagnetoelasticfield_param_18
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd1, [addmagnetoelasticfield_param_0];
	ld.param.u64 	%rd2, [addmagnetoelasticfield_param_1];
	ld.param.u64 	%rd3, [addmagnetoelasticfield_param_2];
	ld.param.u64 	%rd4, [addmagnetoelasticfield_param_3];
	ld.param.u64 	%rd5, [addmagnetoelasticfield_param_4];
	ld.param.u64 	%rd6, [addmagnetoelasticfield_param_5];
	ld.param.u64 	%rd7, [addmagnetoelasticfield_param_6];
	ld.param.u64 	%rd8, [addmagnetoelasticfield_param_7];
	ld.param.u64 	%rd9, [addmagnetoelasticfield_param_8];
	ld.param.u64 	%rd10, [addmagnetoelasticfield_param_9];
	ld.param.u64 	%rd11, [addmagnetoelasticfield_param_10];
	ld.param.u64 	%rd12, [addmagnetoelasticfield_param_11];
	ld.param.u64 	%rd13, [addmagnetoelasticfield_param_12];
	ld.param.f32 	%f51, [addmagnetoelasticfield_param_13];
	ld.param.u64 	%rd14, [addmagnetoelasticfield_param_14];
	ld.param.f32 	%f52, [addmagnetoelasticfield_param_15];
	ld.param.u64 	%rd15, [addmagnetoelasticfield_param_16];
	ld.param.f32 	%f49, [addmagnetoelasticfield_param_17];
	ld.param.u32 	%r2, [addmagnetoelasticfield_param_18];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_10;

	cvta.to.global.u64 	%rd16, %rd7;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.f32 	%f1, [%rd18];
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd17;
	ld.global.f32 	%f2, [%rd20];
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd17;
	ld.global.f32 	%f3, [%rd22];
	cvta.to.global.u64 	%rd23, %rd10;
	add.s64 	%rd24, %rd23, %rd17;
	ld.global.f32 	%f4, [%rd24];
	cvta.to.global.u64 	%rd25, %rd12;
	add.s64 	%rd26, %rd25, %rd17;
	ld.global.f32 	%f5, [%rd26];
	cvta.to.global.u64 	%rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd17;
	ld.global.f32 	%f6, [%rd28];
	setp.eq.s64	%p2, %rd15, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd29, %rd15;
	add.s64 	%rd31, %rd29, %rd17;
	ld.global.f32 	%f18, [%rd31];
	mul.f32 	%f49, %f18, %f49;

BB0_3:
	setp.eq.f32	%p3, %f49, 0f00000000;
	mov.f32 	%f50, 0f00000000;
	@%p3 bra 	BB0_5;

	rcp.rn.f32 	%f50, %f49;

BB0_5:
	setp.eq.s64	%p4, %rd13, 0;
	@%p4 bra 	BB0_7;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd17;
	ld.global.f32 	%f20, [%rd34];
	mul.f32 	%f51, %f20, %f51;

BB0_7:
	setp.eq.s64	%p5, %rd14, 0;
	@%p5 bra 	BB0_9;

	cvta.to.global.u64 	%rd35, %rd14;
	add.s64 	%rd37, %rd35, %rd17;
	ld.global.f32 	%f21, [%rd37];
	mul.f32 	%f52, %f21, %f52;

BB0_9:
	cvta.to.global.u64 	%rd38, %rd4;
	add.s64 	%rd40, %rd38, %rd17;
	cvta.to.global.u64 	%rd41, %rd5;
	add.s64 	%rd42, %rd41, %rd17;
	cvta.to.global.u64 	%rd43, %rd6;
	add.s64 	%rd44, %rd43, %rd17;
	mul.f32 	%f22, %f50, %f51;
	fma.rn.f32 	%f23, %f50, %f51, %f22;
	ld.global.f32 	%f24, [%rd40];
	mul.f32 	%f25, %f23, %f24;
	ld.global.f32 	%f26, [%rd42];
	ld.global.f32 	%f27, [%rd44];
	mul.f32 	%f28, %f5, %f27;
	fma.rn.f32 	%f29, %f4, %f26, %f28;
	mul.f32 	%f30, %f50, %f52;
	mul.f32 	%f31, %f30, %f29;
	fma.rn.f32 	%f32, %f1, %f25, %f31;
	cvta.to.global.u64 	%rd45, %rd1;
	add.s64 	%rd46, %rd45, %rd17;
	ld.global.f32 	%f33, [%rd46];
	sub.f32 	%f34, %f33, %f32;
	st.global.f32 	[%rd46], %f34;
	mul.f32 	%f35, %f23, %f26;
	mul.f32 	%f36, %f6, %f27;
	fma.rn.f32 	%f37, %f4, %f24, %f36;
	mul.f32 	%f38, %f30, %f37;
	fma.rn.f32 	%f39, %f2, %f35, %f38;
	cvta.to.global.u64 	%rd47, %rd2;
	add.s64 	%rd48, %rd47, %rd17;
	ld.global.f32 	%f40, [%rd48];
	sub.f32 	%f41, %f40, %f39;
	st.global.f32 	[%rd48], %f41;
	mul.f32 	%f42, %f23, %f27;
	mul.f32 	%f43, %f6, %f26;
	fma.rn.f32 	%f44, %f5, %f24, %f43;
	mul.f32 	%f45, %f30, %f44;
	fma.rn.f32 	%f46, %f3, %f42, %f45;
	cvta.to.global.u64 	%rd49, %rd3;
	add.s64 	%rd50, %rd49, %rd17;
	ld.global.f32 	%f47, [%rd50];
	sub.f32 	%f48, %f47, %f46;
	st.global.f32 	[%rd50], %f48;

BB0_10:
	ret;
}


`
   addmagnetoelasticfield_ptx_35 = `
.version 6.3
.target sm_35
.address_size 64

	// .globl	addmagnetoelasticfield

.visible .entry addmagnetoelasticfield(
	.param .u64 addmagnetoelasticfield_param_0,
	.param .u64 addmagnetoelasticfield_param_1,
	.param .u64 addmagnetoelasticfield_param_2,
	.param .u64 addmagnetoelasticfield_param_3,
	.param .u64 addmagnetoelasticfield_param_4,
	.param .u64 addmagnetoelasticfield_param_5,
	.param .u64 addmagnetoelasticfield_param_6,
	.param .u64 addmagnetoelasticfield_param_7,
	.param .u64 addmagnetoelasticfield_param_8,
	.param .u64 addmagnetoelasticfield_param_9,
	.param .u64 addmagnetoelasticfield_param_10,
	.param .u64 addmagnetoelasticfield_param_11,
	.param .u64 addmagnetoelasticfield_param_12,
	.param .f32 addmagnetoelasticfield_param_13,
	.param .u64 addmagnetoelasticfield_param_14,
	.param .f32 addmagnetoelasticfield_param_15,
	.param .u64 addmagnetoelasticfield_param_16,
	.param .f32 addmagnetoelasticfield_param_17,
	.param .u32 addmagnetoelasticfield_param_18
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd1, [addmagnetoelasticfield_param_0];
	ld.param.u64 	%rd2, [addmagnetoelasticfield_param_1];
	ld.param.u64 	%rd3, [addmagnetoelasticfield_param_2];
	ld.param.u64 	%rd4, [addmagnetoelasticfield_param_3];
	ld.param.u64 	%rd5, [addmagnetoelasticfield_param_4];
	ld.param.u64 	%rd6, [addmagnetoelasticfield_param_5];
	ld.param.u64 	%rd7, [addmagnetoelasticfield_param_6];
	ld.param.u64 	%rd8, [addmagnetoelasticfield_param_7];
	ld.param.u64 	%rd9, [addmagnetoelasticfield_param_8];
	ld.param.u64 	%rd10, [addmagnetoelasticfield_param_9];
	ld.param.u64 	%rd11, [addmagnetoelasticfield_param_10];
	ld.param.u64 	%rd12, [addmagnetoelasticfield_param_11];
	ld.param.u64 	%rd13, [addmagnetoelasticfield_param_12];
	ld.param.f32 	%f51, [addmagnetoelasticfield_param_13];
	ld.param.u64 	%rd14, [addmagnetoelasticfield_param_14];
	ld.param.f32 	%f52, [addmagnetoelasticfield_param_15];
	ld.param.u64 	%rd15, [addmagnetoelasticfield_param_16];
	ld.param.f32 	%f49, [addmagnetoelasticfield_param_17];
	ld.param.u32 	%r2, [addmagnetoelasticfield_param_18];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_10;

	cvta.to.global.u64 	%rd16, %rd7;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.nc.f32 	%f1, [%rd18];
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd17;
	ld.global.nc.f32 	%f2, [%rd20];
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd17;
	ld.global.nc.f32 	%f3, [%rd22];
	cvta.to.global.u64 	%rd23, %rd10;
	add.s64 	%rd24, %rd23, %rd17;
	ld.global.nc.f32 	%f4, [%rd24];
	cvta.to.global.u64 	%rd25, %rd12;
	add.s64 	%rd26, %rd25, %rd17;
	ld.global.nc.f32 	%f5, [%rd26];
	cvta.to.global.u64 	%rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd17;
	ld.global.nc.f32 	%f6, [%rd28];
	setp.eq.s64	%p2, %rd15, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd29, %rd15;
	add.s64 	%rd31, %rd29, %rd17;
	ld.global.nc.f32 	%f18, [%rd31];
	mul.f32 	%f49, %f18, %f49;

BB0_3:
	setp.eq.f32	%p3, %f49, 0f00000000;
	mov.f32 	%f50, 0f00000000;
	@%p3 bra 	BB0_5;

	rcp.rn.f32 	%f50, %f49;

BB0_5:
	setp.eq.s64	%p4, %rd13, 0;
	@%p4 bra 	BB0_7;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd17;
	ld.global.nc.f32 	%f20, [%rd34];
	mul.f32 	%f51, %f20, %f51;

BB0_7:
	setp.eq.s64	%p5, %rd14, 0;
	@%p5 bra 	BB0_9;

	cvta.to.global.u64 	%rd35, %rd14;
	add.s64 	%rd37, %rd35, %rd17;
	ld.global.nc.f32 	%f21, [%rd37];
	mul.f32 	%f52, %f21, %f52;

BB0_9:
	cvta.to.global.u64 	%rd38, %rd4;
	add.s64 	%rd40, %rd38, %rd17;
	cvta.to.global.u64 	%rd41, %rd5;
	add.s64 	%rd42, %rd41, %rd17;
	cvta.to.global.u64 	%rd43, %rd6;
	add.s64 	%rd44, %rd43, %rd17;
	mul.f32 	%f22, %f50, %f51;
	fma.rn.f32 	%f23, %f50, %f51, %f22;
	ld.global.nc.f32 	%f24, [%rd40];
	mul.f32 	%f25, %f23, %f24;
	ld.global.nc.f32 	%f26, [%rd42];
	ld.global.nc.f32 	%f27, [%rd44];
	mul.f32 	%f28, %f5, %f27;
	fma.rn.f32 	%f29, %f4, %f26, %f28;
	mul.f32 	%f30, %f50, %f52;
	mul.f32 	%f31, %f30, %f29;
	fma.rn.f32 	%f32, %f1, %f25, %f31;
	cvta.to.global.u64 	%rd45, %rd1;
	add.s64 	%rd46, %rd45, %rd17;
	ld.global.f32 	%f33, [%rd46];
	sub.f32 	%f34, %f33, %f32;
	st.global.f32 	[%rd46], %f34;
	mul.f32 	%f35, %f23, %f26;
	mul.f32 	%f36, %f6, %f27;
	fma.rn.f32 	%f37, %f4, %f24, %f36;
	mul.f32 	%f38, %f30, %f37;
	fma.rn.f32 	%f39, %f2, %f35, %f38;
	cvta.to.global.u64 	%rd47, %rd2;
	add.s64 	%rd48, %rd47, %rd17;
	ld.global.f32 	%f40, [%rd48];
	sub.f32 	%f41, %f40, %f39;
	st.global.f32 	[%rd48], %f41;
	mul.f32 	%f42, %f23, %f27;
	mul.f32 	%f43, %f6, %f26;
	fma.rn.f32 	%f44, %f5, %f24, %f43;
	mul.f32 	%f45, %f30, %f44;
	fma.rn.f32 	%f46, %f3, %f42, %f45;
	cvta.to.global.u64 	%rd49, %rd3;
	add.s64 	%rd50, %rd49, %rd17;
	ld.global.f32 	%f47, [%rd50];
	sub.f32 	%f48, %f47, %f46;
	st.global.f32 	[%rd50], %f48;

BB0_10:
	ret;
}


`
   addmagnetoelasticfield_ptx_37 = `
.version 6.3
.target sm_37
.address_size 64

	// .globl	addmagnetoelasticfield

.visible .entry addmagnetoelasticfield(
	.param .u64 addmagnetoelasticfield_param_0,
	.param .u64 addmagnetoelasticfield_param_1,
	.param .u64 addmagnetoelasticfield_param_2,
	.param .u64 addmagnetoelasticfield_param_3,
	.param .u64 addmagnetoelasticfield_param_4,
	.param .u64 addmagnetoelasticfield_param_5,
	.param .u64 addmagnetoelasticfield_param_6,
	.param .u64 addmagnetoelasticfield_param_7,
	.param .u64 addmagnetoelasticfield_param_8,
	.param .u64 addmagnetoelasticfield_param_9,
	.param .u64 addmagnetoelasticfield_param_10,
	.param .u64 addmagnetoelasticfield_param_11,
	.param .u64 addmagnetoelasticfield_param_12,
	.param .f32 addmagnetoelasticfield_param_13,
	.param .u64 addmagnetoelasticfield_param_14,
	.param .f32 addmagnetoelasticfield_param_15,
	.param .u64 addmagnetoelasticfield_param_16,
	.param .f32 addmagnetoelasticfield_param_17,
	.param .u32 addmagnetoelasticfield_param_18
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd1, [addmagnetoelasticfield_param_0];
	ld.param.u64 	%rd2, [addmagnetoelasticfield_param_1];
	ld.param.u64 	%rd3, [addmagnetoelasticfield_param_2];
	ld.param.u64 	%rd4, [addmagnetoelasticfield_param_3];
	ld.param.u64 	%rd5, [addmagnetoelasticfield_param_4];
	ld.param.u64 	%rd6, [addmagnetoelasticfield_param_5];
	ld.param.u64 	%rd7, [addmagnetoelasticfield_param_6];
	ld.param.u64 	%rd8, [addmagnetoelasticfield_param_7];
	ld.param.u64 	%rd9, [addmagnetoelasticfield_param_8];
	ld.param.u64 	%rd10, [addmagnetoelasticfield_param_9];
	ld.param.u64 	%rd11, [addmagnetoelasticfield_param_10];
	ld.param.u64 	%rd12, [addmagnetoelasticfield_param_11];
	ld.param.u64 	%rd13, [addmagnetoelasticfield_param_12];
	ld.param.f32 	%f51, [addmagnetoelasticfield_param_13];
	ld.param.u64 	%rd14, [addmagnetoelasticfield_param_14];
	ld.param.f32 	%f52, [addmagnetoelasticfield_param_15];
	ld.param.u64 	%rd15, [addmagnetoelasticfield_param_16];
	ld.param.f32 	%f49, [addmagnetoelasticfield_param_17];
	ld.param.u32 	%r2, [addmagnetoelasticfield_param_18];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_10;

	cvta.to.global.u64 	%rd16, %rd7;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.nc.f32 	%f1, [%rd18];
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd17;
	ld.global.nc.f32 	%f2, [%rd20];
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd17;
	ld.global.nc.f32 	%f3, [%rd22];
	cvta.to.global.u64 	%rd23, %rd10;
	add.s64 	%rd24, %rd23, %rd17;
	ld.global.nc.f32 	%f4, [%rd24];
	cvta.to.global.u64 	%rd25, %rd12;
	add.s64 	%rd26, %rd25, %rd17;
	ld.global.nc.f32 	%f5, [%rd26];
	cvta.to.global.u64 	%rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd17;
	ld.global.nc.f32 	%f6, [%rd28];
	setp.eq.s64	%p2, %rd15, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd29, %rd15;
	add.s64 	%rd31, %rd29, %rd17;
	ld.global.nc.f32 	%f18, [%rd31];
	mul.f32 	%f49, %f18, %f49;

BB0_3:
	setp.eq.f32	%p3, %f49, 0f00000000;
	mov.f32 	%f50, 0f00000000;
	@%p3 bra 	BB0_5;

	rcp.rn.f32 	%f50, %f49;

BB0_5:
	setp.eq.s64	%p4, %rd13, 0;
	@%p4 bra 	BB0_7;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd17;
	ld.global.nc.f32 	%f20, [%rd34];
	mul.f32 	%f51, %f20, %f51;

BB0_7:
	setp.eq.s64	%p5, %rd14, 0;
	@%p5 bra 	BB0_9;

	cvta.to.global.u64 	%rd35, %rd14;
	add.s64 	%rd37, %rd35, %rd17;
	ld.global.nc.f32 	%f21, [%rd37];
	mul.f32 	%f52, %f21, %f52;

BB0_9:
	cvta.to.global.u64 	%rd38, %rd4;
	add.s64 	%rd40, %rd38, %rd17;
	cvta.to.global.u64 	%rd41, %rd5;
	add.s64 	%rd42, %rd41, %rd17;
	cvta.to.global.u64 	%rd43, %rd6;
	add.s64 	%rd44, %rd43, %rd17;
	mul.f32 	%f22, %f50, %f51;
	fma.rn.f32 	%f23, %f50, %f51, %f22;
	ld.global.nc.f32 	%f24, [%rd40];
	mul.f32 	%f25, %f23, %f24;
	ld.global.nc.f32 	%f26, [%rd42];
	ld.global.nc.f32 	%f27, [%rd44];
	mul.f32 	%f28, %f5, %f27;
	fma.rn.f32 	%f29, %f4, %f26, %f28;
	mul.f32 	%f30, %f50, %f52;
	mul.f32 	%f31, %f30, %f29;
	fma.rn.f32 	%f32, %f1, %f25, %f31;
	cvta.to.global.u64 	%rd45, %rd1;
	add.s64 	%rd46, %rd45, %rd17;
	ld.global.f32 	%f33, [%rd46];
	sub.f32 	%f34, %f33, %f32;
	st.global.f32 	[%rd46], %f34;
	mul.f32 	%f35, %f23, %f26;
	mul.f32 	%f36, %f6, %f27;
	fma.rn.f32 	%f37, %f4, %f24, %f36;
	mul.f32 	%f38, %f30, %f37;
	fma.rn.f32 	%f39, %f2, %f35, %f38;
	cvta.to.global.u64 	%rd47, %rd2;
	add.s64 	%rd48, %rd47, %rd17;
	ld.global.f32 	%f40, [%rd48];
	sub.f32 	%f41, %f40, %f39;
	st.global.f32 	[%rd48], %f41;
	mul.f32 	%f42, %f23, %f27;
	mul.f32 	%f43, %f6, %f26;
	fma.rn.f32 	%f44, %f5, %f24, %f43;
	mul.f32 	%f45, %f30, %f44;
	fma.rn.f32 	%f46, %f3, %f42, %f45;
	cvta.to.global.u64 	%rd49, %rd3;
	add.s64 	%rd50, %rd49, %rd17;
	ld.global.f32 	%f47, [%rd50];
	sub.f32 	%f48, %f47, %f46;
	st.global.f32 	[%rd50], %f48;

BB0_10:
	ret;
}


`
   addmagnetoelasticfield_ptx_50 = `
.version 6.3
.target sm_50
.address_size 64

	// .globl	addmagnetoelasticfield

.visible .entry addmagnetoelasticfield(
	.param .u64 addmagnetoelasticfield_param_0,
	.param .u64 addmagnetoelasticfield_param_1,
	.param .u64 addmagnetoelasticfield_param_2,
	.param .u64 addmagnetoelasticfield_param_3,
	.param .u64 addmagnetoelasticfield_param_4,
	.param .u64 addmagnetoelasticfield_param_5,
	.param .u64 addmagnetoelasticfield_param_6,
	.param .u64 addmagnetoelasticfield_param_7,
	.param .u64 addmagnetoelasticfield_param_8,
	.param .u64 addmagnetoelasticfield_param_9,
	.param .u64 addmagnetoelasticfield_param_10,
	.param .u64 addmagnetoelasticfield_param_11,
	.param .u64 addmagnetoelasticfield_param_12,
	.param .f32 addmagnetoelasticfield_param_13,
	.param .u64 addmagnetoelasticfield_param_14,
	.param .f32 addmagnetoelasticfield_param_15,
	.param .u64 addmagnetoelasticfield_param_16,
	.param .f32 addmagnetoelasticfield_param_17,
	.param .u32 addmagnetoelasticfield_param_18
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd1, [addmagnetoelasticfield_param_0];
	ld.param.u64 	%rd2, [addmagnetoelasticfield_param_1];
	ld.param.u64 	%rd3, [addmagnetoelasticfield_param_2];
	ld.param.u64 	%rd4, [addmagnetoelasticfield_param_3];
	ld.param.u64 	%rd5, [addmagnetoelasticfield_param_4];
	ld.param.u64 	%rd6, [addmagnetoelasticfield_param_5];
	ld.param.u64 	%rd7, [addmagnetoelasticfield_param_6];
	ld.param.u64 	%rd8, [addmagnetoelasticfield_param_7];
	ld.param.u64 	%rd9, [addmagnetoelasticfield_param_8];
	ld.param.u64 	%rd10, [addmagnetoelasticfield_param_9];
	ld.param.u64 	%rd11, [addmagnetoelasticfield_param_10];
	ld.param.u64 	%rd12, [addmagnetoelasticfield_param_11];
	ld.param.u64 	%rd13, [addmagnetoelasticfield_param_12];
	ld.param.f32 	%f51, [addmagnetoelasticfield_param_13];
	ld.param.u64 	%rd14, [addmagnetoelasticfield_param_14];
	ld.param.f32 	%f52, [addmagnetoelasticfield_param_15];
	ld.param.u64 	%rd15, [addmagnetoelasticfield_param_16];
	ld.param.f32 	%f49, [addmagnetoelasticfield_param_17];
	ld.param.u32 	%r2, [addmagnetoelasticfield_param_18];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_10;

	cvta.to.global.u64 	%rd16, %rd7;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.nc.f32 	%f1, [%rd18];
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd17;
	ld.global.nc.f32 	%f2, [%rd20];
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd17;
	ld.global.nc.f32 	%f3, [%rd22];
	cvta.to.global.u64 	%rd23, %rd10;
	add.s64 	%rd24, %rd23, %rd17;
	ld.global.nc.f32 	%f4, [%rd24];
	cvta.to.global.u64 	%rd25, %rd12;
	add.s64 	%rd26, %rd25, %rd17;
	ld.global.nc.f32 	%f5, [%rd26];
	cvta.to.global.u64 	%rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd17;
	ld.global.nc.f32 	%f6, [%rd28];
	setp.eq.s64	%p2, %rd15, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd29, %rd15;
	add.s64 	%rd31, %rd29, %rd17;
	ld.global.nc.f32 	%f18, [%rd31];
	mul.f32 	%f49, %f18, %f49;

BB0_3:
	setp.eq.f32	%p3, %f49, 0f00000000;
	mov.f32 	%f50, 0f00000000;
	@%p3 bra 	BB0_5;

	rcp.rn.f32 	%f50, %f49;

BB0_5:
	setp.eq.s64	%p4, %rd13, 0;
	@%p4 bra 	BB0_7;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd17;
	ld.global.nc.f32 	%f20, [%rd34];
	mul.f32 	%f51, %f20, %f51;

BB0_7:
	setp.eq.s64	%p5, %rd14, 0;
	@%p5 bra 	BB0_9;

	cvta.to.global.u64 	%rd35, %rd14;
	add.s64 	%rd37, %rd35, %rd17;
	ld.global.nc.f32 	%f21, [%rd37];
	mul.f32 	%f52, %f21, %f52;

BB0_9:
	cvta.to.global.u64 	%rd38, %rd4;
	add.s64 	%rd40, %rd38, %rd17;
	cvta.to.global.u64 	%rd41, %rd5;
	add.s64 	%rd42, %rd41, %rd17;
	cvta.to.global.u64 	%rd43, %rd6;
	add.s64 	%rd44, %rd43, %rd17;
	mul.f32 	%f22, %f50, %f51;
	fma.rn.f32 	%f23, %f50, %f51, %f22;
	ld.global.nc.f32 	%f24, [%rd40];
	mul.f32 	%f25, %f23, %f24;
	ld.global.nc.f32 	%f26, [%rd42];
	ld.global.nc.f32 	%f27, [%rd44];
	mul.f32 	%f28, %f5, %f27;
	fma.rn.f32 	%f29, %f4, %f26, %f28;
	mul.f32 	%f30, %f50, %f52;
	mul.f32 	%f31, %f30, %f29;
	fma.rn.f32 	%f32, %f1, %f25, %f31;
	cvta.to.global.u64 	%rd45, %rd1;
	add.s64 	%rd46, %rd45, %rd17;
	ld.global.f32 	%f33, [%rd46];
	sub.f32 	%f34, %f33, %f32;
	st.global.f32 	[%rd46], %f34;
	mul.f32 	%f35, %f23, %f26;
	mul.f32 	%f36, %f6, %f27;
	fma.rn.f32 	%f37, %f4, %f24, %f36;
	mul.f32 	%f38, %f30, %f37;
	fma.rn.f32 	%f39, %f2, %f35, %f38;
	cvta.to.global.u64 	%rd47, %rd2;
	add.s64 	%rd48, %rd47, %rd17;
	ld.global.f32 	%f40, [%rd48];
	sub.f32 	%f41, %f40, %f39;
	st.global.f32 	[%rd48], %f41;
	mul.f32 	%f42, %f23, %f27;
	mul.f32 	%f43, %f6, %f26;
	fma.rn.f32 	%f44, %f5, %f24, %f43;
	mul.f32 	%f45, %f30, %f44;
	fma.rn.f32 	%f46, %f3, %f42, %f45;
	cvta.to.global.u64 	%rd49, %rd3;
	add.s64 	%rd50, %rd49, %rd17;
	ld.global.f32 	%f47, [%rd50];
	sub.f32 	%f48, %f47, %f46;
	st.global.f32 	[%rd50], %f48;

BB0_10:
	ret;
}


`
   addmagnetoelasticfield_ptx_52 = `
.version 6.3
.target sm_52
.address_size 64

	// .globl	addmagnetoelasticfield

.visible .entry addmagnetoelasticfield(
	.param .u64 addmagnetoelasticfield_param_0,
	.param .u64 addmagnetoelasticfield_param_1,
	.param .u64 addmagnetoelasticfield_param_2,
	.param .u64 addmagnetoelasticfield_param_3,
	.param .u64 addmagnetoelasticfield_param_4,
	.param .u64 addmagnetoelasticfield_param_5,
	.param .u64 addmagnetoelasticfield_param_6,
	.param .u64 addmagnetoelasticfield_param_7,
	.param .u64 addmagnetoelasticfield_param_8,
	.param .u64 addmagnetoelasticfield_param_9,
	.param .u64 addmagnetoelasticfield_param_10,
	.param .u64 addmagnetoelasticfield_param_11,
	.param .u64 addmagnetoelasticfield_param_12,
	.param .f32 addmagnetoelasticfield_param_13,
	.param .u64 addmagnetoelasticfield_param_14,
	.param .f32 addmagnetoelasticfield_param_15,
	.param .u64 addmagnetoelasticfield_param_16,
	.param .f32 addmagnetoelasticfield_param_17,
	.param .u32 addmagnetoelasticfield_param_18
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd1, [addmagnetoelasticfield_param_0];
	ld.param.u64 	%rd2, [addmagnetoelasticfield_param_1];
	ld.param.u64 	%rd3, [addmagnetoelasticfield_param_2];
	ld.param.u64 	%rd4, [addmagnetoelasticfield_param_3];
	ld.param.u64 	%rd5, [addmagnetoelasticfield_param_4];
	ld.param.u64 	%rd6, [addmagnetoelasticfield_param_5];
	ld.param.u64 	%rd7, [addmagnetoelasticfield_param_6];
	ld.param.u64 	%rd8, [addmagnetoelasticfield_param_7];
	ld.param.u64 	%rd9, [addmagnetoelasticfield_param_8];
	ld.param.u64 	%rd10, [addmagnetoelasticfield_param_9];
	ld.param.u64 	%rd11, [addmagnetoelasticfield_param_10];
	ld.param.u64 	%rd12, [addmagnetoelasticfield_param_11];
	ld.param.u64 	%rd13, [addmagnetoelasticfield_param_12];
	ld.param.f32 	%f51, [addmagnetoelasticfield_param_13];
	ld.param.u64 	%rd14, [addmagnetoelasticfield_param_14];
	ld.param.f32 	%f52, [addmagnetoelasticfield_param_15];
	ld.param.u64 	%rd15, [addmagnetoelasticfield_param_16];
	ld.param.f32 	%f49, [addmagnetoelasticfield_param_17];
	ld.param.u32 	%r2, [addmagnetoelasticfield_param_18];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_10;

	cvta.to.global.u64 	%rd16, %rd7;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.nc.f32 	%f1, [%rd18];
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd17;
	ld.global.nc.f32 	%f2, [%rd20];
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd17;
	ld.global.nc.f32 	%f3, [%rd22];
	cvta.to.global.u64 	%rd23, %rd10;
	add.s64 	%rd24, %rd23, %rd17;
	ld.global.nc.f32 	%f4, [%rd24];
	cvta.to.global.u64 	%rd25, %rd12;
	add.s64 	%rd26, %rd25, %rd17;
	ld.global.nc.f32 	%f5, [%rd26];
	cvta.to.global.u64 	%rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd17;
	ld.global.nc.f32 	%f6, [%rd28];
	setp.eq.s64	%p2, %rd15, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd29, %rd15;
	add.s64 	%rd31, %rd29, %rd17;
	ld.global.nc.f32 	%f18, [%rd31];
	mul.f32 	%f49, %f18, %f49;

BB0_3:
	setp.eq.f32	%p3, %f49, 0f00000000;
	mov.f32 	%f50, 0f00000000;
	@%p3 bra 	BB0_5;

	rcp.rn.f32 	%f50, %f49;

BB0_5:
	setp.eq.s64	%p4, %rd13, 0;
	@%p4 bra 	BB0_7;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd17;
	ld.global.nc.f32 	%f20, [%rd34];
	mul.f32 	%f51, %f20, %f51;

BB0_7:
	setp.eq.s64	%p5, %rd14, 0;
	@%p5 bra 	BB0_9;

	cvta.to.global.u64 	%rd35, %rd14;
	add.s64 	%rd37, %rd35, %rd17;
	ld.global.nc.f32 	%f21, [%rd37];
	mul.f32 	%f52, %f21, %f52;

BB0_9:
	cvta.to.global.u64 	%rd38, %rd4;
	add.s64 	%rd40, %rd38, %rd17;
	cvta.to.global.u64 	%rd41, %rd5;
	add.s64 	%rd42, %rd41, %rd17;
	cvta.to.global.u64 	%rd43, %rd6;
	add.s64 	%rd44, %rd43, %rd17;
	mul.f32 	%f22, %f50, %f51;
	fma.rn.f32 	%f23, %f50, %f51, %f22;
	ld.global.nc.f32 	%f24, [%rd40];
	mul.f32 	%f25, %f23, %f24;
	ld.global.nc.f32 	%f26, [%rd42];
	ld.global.nc.f32 	%f27, [%rd44];
	mul.f32 	%f28, %f5, %f27;
	fma.rn.f32 	%f29, %f4, %f26, %f28;
	mul.f32 	%f30, %f50, %f52;
	mul.f32 	%f31, %f30, %f29;
	fma.rn.f32 	%f32, %f1, %f25, %f31;
	cvta.to.global.u64 	%rd45, %rd1;
	add.s64 	%rd46, %rd45, %rd17;
	ld.global.f32 	%f33, [%rd46];
	sub.f32 	%f34, %f33, %f32;
	st.global.f32 	[%rd46], %f34;
	mul.f32 	%f35, %f23, %f26;
	mul.f32 	%f36, %f6, %f27;
	fma.rn.f32 	%f37, %f4, %f24, %f36;
	mul.f32 	%f38, %f30, %f37;
	fma.rn.f32 	%f39, %f2, %f35, %f38;
	cvta.to.global.u64 	%rd47, %rd2;
	add.s64 	%rd48, %rd47, %rd17;
	ld.global.f32 	%f40, [%rd48];
	sub.f32 	%f41, %f40, %f39;
	st.global.f32 	[%rd48], %f41;
	mul.f32 	%f42, %f23, %f27;
	mul.f32 	%f43, %f6, %f26;
	fma.rn.f32 	%f44, %f5, %f24, %f43;
	mul.f32 	%f45, %f30, %f44;
	fma.rn.f32 	%f46, %f3, %f42, %f45;
	cvta.to.global.u64 	%rd49, %rd3;
	add.s64 	%rd50, %rd49, %rd17;
	ld.global.f32 	%f47, [%rd50];
	sub.f32 	%f48, %f47, %f46;
	st.global.f32 	[%rd50], %f48;

BB0_10:
	ret;
}


`
   addmagnetoelasticfield_ptx_53 = `
.version 6.3
.target sm_53
.address_size 64

	// .globl	addmagnetoelasticfield

.visible .entry addmagnetoelasticfield(
	.param .u64 addmagnetoelasticfield_param_0,
	.param .u64 addmagnetoelasticfield_param_1,
	.param .u64 addmagnetoelasticfield_param_2,
	.param .u64 addmagnetoelasticfield_param_3,
	.param .u64 addmagnetoelasticfield_param_4,
	.param .u64 addmagnetoelasticfield_param_5,
	.param .u64 addmagnetoelasticfield_param_6,
	.param .u64 addmagnetoelasticfield_param_7,
	.param .u64 addmagnetoelasticfield_param_8,
	.param .u64 addmagnetoelasticfield_param_9,
	.param .u64 addmagnetoelasticfield_param_10,
	.param .u64 addmagnetoelasticfield_param_11,
	.param .u64 addmagnetoelasticfield_param_12,
	.param .f32 addmagnetoelasticfield_param_13,
	.param .u64 addmagnetoelasticfield_param_14,
	.param .f32 addmagnetoelasticfield_param_15,
	.param .u64 addmagnetoelasticfield_param_16,
	.param .f32 addmagnetoelasticfield_param_17,
	.param .u32 addmagnetoelasticfield_param_18
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd1, [addmagnetoelasticfield_param_0];
	ld.param.u64 	%rd2, [addmagnetoelasticfield_param_1];
	ld.param.u64 	%rd3, [addmagnetoelasticfield_param_2];
	ld.param.u64 	%rd4, [addmagnetoelasticfield_param_3];
	ld.param.u64 	%rd5, [addmagnetoelasticfield_param_4];
	ld.param.u64 	%rd6, [addmagnetoelasticfield_param_5];
	ld.param.u64 	%rd7, [addmagnetoelasticfield_param_6];
	ld.param.u64 	%rd8, [addmagnetoelasticfield_param_7];
	ld.param.u64 	%rd9, [addmagnetoelasticfield_param_8];
	ld.param.u64 	%rd10, [addmagnetoelasticfield_param_9];
	ld.param.u64 	%rd11, [addmagnetoelasticfield_param_10];
	ld.param.u64 	%rd12, [addmagnetoelasticfield_param_11];
	ld.param.u64 	%rd13, [addmagnetoelasticfield_param_12];
	ld.param.f32 	%f51, [addmagnetoelasticfield_param_13];
	ld.param.u64 	%rd14, [addmagnetoelasticfield_param_14];
	ld.param.f32 	%f52, [addmagnetoelasticfield_param_15];
	ld.param.u64 	%rd15, [addmagnetoelasticfield_param_16];
	ld.param.f32 	%f49, [addmagnetoelasticfield_param_17];
	ld.param.u32 	%r2, [addmagnetoelasticfield_param_18];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_10;

	cvta.to.global.u64 	%rd16, %rd7;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.nc.f32 	%f1, [%rd18];
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd17;
	ld.global.nc.f32 	%f2, [%rd20];
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd17;
	ld.global.nc.f32 	%f3, [%rd22];
	cvta.to.global.u64 	%rd23, %rd10;
	add.s64 	%rd24, %rd23, %rd17;
	ld.global.nc.f32 	%f4, [%rd24];
	cvta.to.global.u64 	%rd25, %rd12;
	add.s64 	%rd26, %rd25, %rd17;
	ld.global.nc.f32 	%f5, [%rd26];
	cvta.to.global.u64 	%rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd17;
	ld.global.nc.f32 	%f6, [%rd28];
	setp.eq.s64	%p2, %rd15, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd29, %rd15;
	add.s64 	%rd31, %rd29, %rd17;
	ld.global.nc.f32 	%f18, [%rd31];
	mul.f32 	%f49, %f18, %f49;

BB0_3:
	setp.eq.f32	%p3, %f49, 0f00000000;
	mov.f32 	%f50, 0f00000000;
	@%p3 bra 	BB0_5;

	rcp.rn.f32 	%f50, %f49;

BB0_5:
	setp.eq.s64	%p4, %rd13, 0;
	@%p4 bra 	BB0_7;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd17;
	ld.global.nc.f32 	%f20, [%rd34];
	mul.f32 	%f51, %f20, %f51;

BB0_7:
	setp.eq.s64	%p5, %rd14, 0;
	@%p5 bra 	BB0_9;

	cvta.to.global.u64 	%rd35, %rd14;
	add.s64 	%rd37, %rd35, %rd17;
	ld.global.nc.f32 	%f21, [%rd37];
	mul.f32 	%f52, %f21, %f52;

BB0_9:
	cvta.to.global.u64 	%rd38, %rd4;
	add.s64 	%rd40, %rd38, %rd17;
	cvta.to.global.u64 	%rd41, %rd5;
	add.s64 	%rd42, %rd41, %rd17;
	cvta.to.global.u64 	%rd43, %rd6;
	add.s64 	%rd44, %rd43, %rd17;
	mul.f32 	%f22, %f50, %f51;
	fma.rn.f32 	%f23, %f50, %f51, %f22;
	ld.global.nc.f32 	%f24, [%rd40];
	mul.f32 	%f25, %f23, %f24;
	ld.global.nc.f32 	%f26, [%rd42];
	ld.global.nc.f32 	%f27, [%rd44];
	mul.f32 	%f28, %f5, %f27;
	fma.rn.f32 	%f29, %f4, %f26, %f28;
	mul.f32 	%f30, %f50, %f52;
	mul.f32 	%f31, %f30, %f29;
	fma.rn.f32 	%f32, %f1, %f25, %f31;
	cvta.to.global.u64 	%rd45, %rd1;
	add.s64 	%rd46, %rd45, %rd17;
	ld.global.f32 	%f33, [%rd46];
	sub.f32 	%f34, %f33, %f32;
	st.global.f32 	[%rd46], %f34;
	mul.f32 	%f35, %f23, %f26;
	mul.f32 	%f36, %f6, %f27;
	fma.rn.f32 	%f37, %f4, %f24, %f36;
	mul.f32 	%f38, %f30, %f37;
	fma.rn.f32 	%f39, %f2, %f35, %f38;
	cvta.to.global.u64 	%rd47, %rd2;
	add.s64 	%rd48, %rd47, %rd17;
	ld.global.f32 	%f40, [%rd48];
	sub.f32 	%f41, %f40, %f39;
	st.global.f32 	[%rd48], %f41;
	mul.f32 	%f42, %f23, %f27;
	mul.f32 	%f43, %f6, %f26;
	fma.rn.f32 	%f44, %f5, %f24, %f43;
	mul.f32 	%f45, %f30, %f44;
	fma.rn.f32 	%f46, %f3, %f42, %f45;
	cvta.to.global.u64 	%rd49, %rd3;
	add.s64 	%rd50, %rd49, %rd17;
	ld.global.f32 	%f47, [%rd50];
	sub.f32 	%f48, %f47, %f46;
	st.global.f32 	[%rd50], %f48;

BB0_10:
	ret;
}


`
   addmagnetoelasticfield_ptx_60 = `
.version 6.3
.target sm_60
.address_size 64

	// .globl	addmagnetoelasticfield

.visible .entry addmagnetoelasticfield(
	.param .u64 addmagnetoelasticfield_param_0,
	.param .u64 addmagnetoelasticfield_param_1,
	.param .u64 addmagnetoelasticfield_param_2,
	.param .u64 addmagnetoelasticfield_param_3,
	.param .u64 addmagnetoelasticfield_param_4,
	.param .u64 addmagnetoelasticfield_param_5,
	.param .u64 addmagnetoelasticfield_param_6,
	.param .u64 addmagnetoelasticfield_param_7,
	.param .u64 addmagnetoelasticfield_param_8,
	.param .u64 addmagnetoelasticfield_param_9,
	.param .u64 addmagnetoelasticfield_param_10,
	.param .u64 addmagnetoelasticfield_param_11,
	.param .u64 addmagnetoelasticfield_param_12,
	.param .f32 addmagnetoelasticfield_param_13,
	.param .u64 addmagnetoelasticfield_param_14,
	.param .f32 addmagnetoelasticfield_param_15,
	.param .u64 addmagnetoelasticfield_param_16,
	.param .f32 addmagnetoelasticfield_param_17,
	.param .u32 addmagnetoelasticfield_param_18
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd1, [addmagnetoelasticfield_param_0];
	ld.param.u64 	%rd2, [addmagnetoelasticfield_param_1];
	ld.param.u64 	%rd3, [addmagnetoelasticfield_param_2];
	ld.param.u64 	%rd4, [addmagnetoelasticfield_param_3];
	ld.param.u64 	%rd5, [addmagnetoelasticfield_param_4];
	ld.param.u64 	%rd6, [addmagnetoelasticfield_param_5];
	ld.param.u64 	%rd7, [addmagnetoelasticfield_param_6];
	ld.param.u64 	%rd8, [addmagnetoelasticfield_param_7];
	ld.param.u64 	%rd9, [addmagnetoelasticfield_param_8];
	ld.param.u64 	%rd10, [addmagnetoelasticfield_param_9];
	ld.param.u64 	%rd11, [addmagnetoelasticfield_param_10];
	ld.param.u64 	%rd12, [addmagnetoelasticfield_param_11];
	ld.param.u64 	%rd13, [addmagnetoelasticfield_param_12];
	ld.param.f32 	%f51, [addmagnetoelasticfield_param_13];
	ld.param.u64 	%rd14, [addmagnetoelasticfield_param_14];
	ld.param.f32 	%f52, [addmagnetoelasticfield_param_15];
	ld.param.u64 	%rd15, [addmagnetoelasticfield_param_16];
	ld.param.f32 	%f49, [addmagnetoelasticfield_param_17];
	ld.param.u32 	%r2, [addmagnetoelasticfield_param_18];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_10;

	cvta.to.global.u64 	%rd16, %rd7;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.nc.f32 	%f1, [%rd18];
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd17;
	ld.global.nc.f32 	%f2, [%rd20];
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd17;
	ld.global.nc.f32 	%f3, [%rd22];
	cvta.to.global.u64 	%rd23, %rd10;
	add.s64 	%rd24, %rd23, %rd17;
	ld.global.nc.f32 	%f4, [%rd24];
	cvta.to.global.u64 	%rd25, %rd12;
	add.s64 	%rd26, %rd25, %rd17;
	ld.global.nc.f32 	%f5, [%rd26];
	cvta.to.global.u64 	%rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd17;
	ld.global.nc.f32 	%f6, [%rd28];
	setp.eq.s64	%p2, %rd15, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd29, %rd15;
	add.s64 	%rd31, %rd29, %rd17;
	ld.global.nc.f32 	%f18, [%rd31];
	mul.f32 	%f49, %f18, %f49;

BB0_3:
	setp.eq.f32	%p3, %f49, 0f00000000;
	mov.f32 	%f50, 0f00000000;
	@%p3 bra 	BB0_5;

	rcp.rn.f32 	%f50, %f49;

BB0_5:
	setp.eq.s64	%p4, %rd13, 0;
	@%p4 bra 	BB0_7;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd17;
	ld.global.nc.f32 	%f20, [%rd34];
	mul.f32 	%f51, %f20, %f51;

BB0_7:
	setp.eq.s64	%p5, %rd14, 0;
	@%p5 bra 	BB0_9;

	cvta.to.global.u64 	%rd35, %rd14;
	add.s64 	%rd37, %rd35, %rd17;
	ld.global.nc.f32 	%f21, [%rd37];
	mul.f32 	%f52, %f21, %f52;

BB0_9:
	cvta.to.global.u64 	%rd38, %rd4;
	add.s64 	%rd40, %rd38, %rd17;
	cvta.to.global.u64 	%rd41, %rd5;
	add.s64 	%rd42, %rd41, %rd17;
	cvta.to.global.u64 	%rd43, %rd6;
	add.s64 	%rd44, %rd43, %rd17;
	mul.f32 	%f22, %f50, %f51;
	fma.rn.f32 	%f23, %f50, %f51, %f22;
	ld.global.nc.f32 	%f24, [%rd40];
	mul.f32 	%f25, %f23, %f24;
	ld.global.nc.f32 	%f26, [%rd42];
	ld.global.nc.f32 	%f27, [%rd44];
	mul.f32 	%f28, %f5, %f27;
	fma.rn.f32 	%f29, %f4, %f26, %f28;
	mul.f32 	%f30, %f50, %f52;
	mul.f32 	%f31, %f30, %f29;
	fma.rn.f32 	%f32, %f1, %f25, %f31;
	cvta.to.global.u64 	%rd45, %rd1;
	add.s64 	%rd46, %rd45, %rd17;
	ld.global.f32 	%f33, [%rd46];
	sub.f32 	%f34, %f33, %f32;
	st.global.f32 	[%rd46], %f34;
	mul.f32 	%f35, %f23, %f26;
	mul.f32 	%f36, %f6, %f27;
	fma.rn.f32 	%f37, %f4, %f24, %f36;
	mul.f32 	%f38, %f30, %f37;
	fma.rn.f32 	%f39, %f2, %f35, %f38;
	cvta.to.global.u64 	%rd47, %rd2;
	add.s64 	%rd48, %rd47, %rd17;
	ld.global.f32 	%f40, [%rd48];
	sub.f32 	%f41, %f40, %f39;
	st.global.f32 	[%rd48], %f41;
	mul.f32 	%f42, %f23, %f27;
	mul.f32 	%f43, %f6, %f26;
	fma.rn.f32 	%f44, %f5, %f24, %f43;
	mul.f32 	%f45, %f30, %f44;
	fma.rn.f32 	%f46, %f3, %f42, %f45;
	cvta.to.global.u64 	%rd49, %rd3;
	add.s64 	%rd50, %rd49, %rd17;
	ld.global.f32 	%f47, [%rd50];
	sub.f32 	%f48, %f47, %f46;
	st.global.f32 	[%rd50], %f48;

BB0_10:
	ret;
}


`
   addmagnetoelasticfield_ptx_61 = `
.version 6.3
.target sm_61
.address_size 64

	// .globl	addmagnetoelasticfield

.visible .entry addmagnetoelasticfield(
	.param .u64 addmagnetoelasticfield_param_0,
	.param .u64 addmagnetoelasticfield_param_1,
	.param .u64 addmagnetoelasticfield_param_2,
	.param .u64 addmagnetoelasticfield_param_3,
	.param .u64 addmagnetoelasticfield_param_4,
	.param .u64 addmagnetoelasticfield_param_5,
	.param .u64 addmagnetoelasticfield_param_6,
	.param .u64 addmagnetoelasticfield_param_7,
	.param .u64 addmagnetoelasticfield_param_8,
	.param .u64 addmagnetoelasticfield_param_9,
	.param .u64 addmagnetoelasticfield_param_10,
	.param .u64 addmagnetoelasticfield_param_11,
	.param .u64 addmagnetoelasticfield_param_12,
	.param .f32 addmagnetoelasticfield_param_13,
	.param .u64 addmagnetoelasticfield_param_14,
	.param .f32 addmagnetoelasticfield_param_15,
	.param .u64 addmagnetoelasticfield_param_16,
	.param .f32 addmagnetoelasticfield_param_17,
	.param .u32 addmagnetoelasticfield_param_18
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd1, [addmagnetoelasticfield_param_0];
	ld.param.u64 	%rd2, [addmagnetoelasticfield_param_1];
	ld.param.u64 	%rd3, [addmagnetoelasticfield_param_2];
	ld.param.u64 	%rd4, [addmagnetoelasticfield_param_3];
	ld.param.u64 	%rd5, [addmagnetoelasticfield_param_4];
	ld.param.u64 	%rd6, [addmagnetoelasticfield_param_5];
	ld.param.u64 	%rd7, [addmagnetoelasticfield_param_6];
	ld.param.u64 	%rd8, [addmagnetoelasticfield_param_7];
	ld.param.u64 	%rd9, [addmagnetoelasticfield_param_8];
	ld.param.u64 	%rd10, [addmagnetoelasticfield_param_9];
	ld.param.u64 	%rd11, [addmagnetoelasticfield_param_10];
	ld.param.u64 	%rd12, [addmagnetoelasticfield_param_11];
	ld.param.u64 	%rd13, [addmagnetoelasticfield_param_12];
	ld.param.f32 	%f51, [addmagnetoelasticfield_param_13];
	ld.param.u64 	%rd14, [addmagnetoelasticfield_param_14];
	ld.param.f32 	%f52, [addmagnetoelasticfield_param_15];
	ld.param.u64 	%rd15, [addmagnetoelasticfield_param_16];
	ld.param.f32 	%f49, [addmagnetoelasticfield_param_17];
	ld.param.u32 	%r2, [addmagnetoelasticfield_param_18];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_10;

	cvta.to.global.u64 	%rd16, %rd7;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.nc.f32 	%f1, [%rd18];
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd17;
	ld.global.nc.f32 	%f2, [%rd20];
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd17;
	ld.global.nc.f32 	%f3, [%rd22];
	cvta.to.global.u64 	%rd23, %rd10;
	add.s64 	%rd24, %rd23, %rd17;
	ld.global.nc.f32 	%f4, [%rd24];
	cvta.to.global.u64 	%rd25, %rd12;
	add.s64 	%rd26, %rd25, %rd17;
	ld.global.nc.f32 	%f5, [%rd26];
	cvta.to.global.u64 	%rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd17;
	ld.global.nc.f32 	%f6, [%rd28];
	setp.eq.s64	%p2, %rd15, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd29, %rd15;
	add.s64 	%rd31, %rd29, %rd17;
	ld.global.nc.f32 	%f18, [%rd31];
	mul.f32 	%f49, %f18, %f49;

BB0_3:
	setp.eq.f32	%p3, %f49, 0f00000000;
	mov.f32 	%f50, 0f00000000;
	@%p3 bra 	BB0_5;

	rcp.rn.f32 	%f50, %f49;

BB0_5:
	setp.eq.s64	%p4, %rd13, 0;
	@%p4 bra 	BB0_7;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd17;
	ld.global.nc.f32 	%f20, [%rd34];
	mul.f32 	%f51, %f20, %f51;

BB0_7:
	setp.eq.s64	%p5, %rd14, 0;
	@%p5 bra 	BB0_9;

	cvta.to.global.u64 	%rd35, %rd14;
	add.s64 	%rd37, %rd35, %rd17;
	ld.global.nc.f32 	%f21, [%rd37];
	mul.f32 	%f52, %f21, %f52;

BB0_9:
	cvta.to.global.u64 	%rd38, %rd4;
	add.s64 	%rd40, %rd38, %rd17;
	cvta.to.global.u64 	%rd41, %rd5;
	add.s64 	%rd42, %rd41, %rd17;
	cvta.to.global.u64 	%rd43, %rd6;
	add.s64 	%rd44, %rd43, %rd17;
	mul.f32 	%f22, %f50, %f51;
	fma.rn.f32 	%f23, %f50, %f51, %f22;
	ld.global.nc.f32 	%f24, [%rd40];
	mul.f32 	%f25, %f23, %f24;
	ld.global.nc.f32 	%f26, [%rd42];
	ld.global.nc.f32 	%f27, [%rd44];
	mul.f32 	%f28, %f5, %f27;
	fma.rn.f32 	%f29, %f4, %f26, %f28;
	mul.f32 	%f30, %f50, %f52;
	mul.f32 	%f31, %f30, %f29;
	fma.rn.f32 	%f32, %f1, %f25, %f31;
	cvta.to.global.u64 	%rd45, %rd1;
	add.s64 	%rd46, %rd45, %rd17;
	ld.global.f32 	%f33, [%rd46];
	sub.f32 	%f34, %f33, %f32;
	st.global.f32 	[%rd46], %f34;
	mul.f32 	%f35, %f23, %f26;
	mul.f32 	%f36, %f6, %f27;
	fma.rn.f32 	%f37, %f4, %f24, %f36;
	mul.f32 	%f38, %f30, %f37;
	fma.rn.f32 	%f39, %f2, %f35, %f38;
	cvta.to.global.u64 	%rd47, %rd2;
	add.s64 	%rd48, %rd47, %rd17;
	ld.global.f32 	%f40, [%rd48];
	sub.f32 	%f41, %f40, %f39;
	st.global.f32 	[%rd48], %f41;
	mul.f32 	%f42, %f23, %f27;
	mul.f32 	%f43, %f6, %f26;
	fma.rn.f32 	%f44, %f5, %f24, %f43;
	mul.f32 	%f45, %f30, %f44;
	fma.rn.f32 	%f46, %f3, %f42, %f45;
	cvta.to.global.u64 	%rd49, %rd3;
	add.s64 	%rd50, %rd49, %rd17;
	ld.global.f32 	%f47, [%rd50];
	sub.f32 	%f48, %f47, %f46;
	st.global.f32 	[%rd50], %f48;

BB0_10:
	ret;
}


`
   addmagnetoelasticfield_ptx_70 = `
.version 6.3
.target sm_70
.address_size 64

	// .globl	addmagnetoelasticfield

.visible .entry addmagnetoelasticfield(
	.param .u64 addmagnetoelasticfield_param_0,
	.param .u64 addmagnetoelasticfield_param_1,
	.param .u64 addmagnetoelasticfield_param_2,
	.param .u64 addmagnetoelasticfield_param_3,
	.param .u64 addmagnetoelasticfield_param_4,
	.param .u64 addmagnetoelasticfield_param_5,
	.param .u64 addmagnetoelasticfield_param_6,
	.param .u64 addmagnetoelasticfield_param_7,
	.param .u64 addmagnetoelasticfield_param_8,
	.param .u64 addmagnetoelasticfield_param_9,
	.param .u64 addmagnetoelasticfield_param_10,
	.param .u64 addmagnetoelasticfield_param_11,
	.param .u64 addmagnetoelasticfield_param_12,
	.param .f32 addmagnetoelasticfield_param_13,
	.param .u64 addmagnetoelasticfield_param_14,
	.param .f32 addmagnetoelasticfield_param_15,
	.param .u64 addmagnetoelasticfield_param_16,
	.param .f32 addmagnetoelasticfield_param_17,
	.param .u32 addmagnetoelasticfield_param_18
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd1, [addmagnetoelasticfield_param_0];
	ld.param.u64 	%rd2, [addmagnetoelasticfield_param_1];
	ld.param.u64 	%rd3, [addmagnetoelasticfield_param_2];
	ld.param.u64 	%rd4, [addmagnetoelasticfield_param_3];
	ld.param.u64 	%rd5, [addmagnetoelasticfield_param_4];
	ld.param.u64 	%rd6, [addmagnetoelasticfield_param_5];
	ld.param.u64 	%rd7, [addmagnetoelasticfield_param_6];
	ld.param.u64 	%rd8, [addmagnetoelasticfield_param_7];
	ld.param.u64 	%rd9, [addmagnetoelasticfield_param_8];
	ld.param.u64 	%rd10, [addmagnetoelasticfield_param_9];
	ld.param.u64 	%rd11, [addmagnetoelasticfield_param_10];
	ld.param.u64 	%rd12, [addmagnetoelasticfield_param_11];
	ld.param.u64 	%rd13, [addmagnetoelasticfield_param_12];
	ld.param.f32 	%f51, [addmagnetoelasticfield_param_13];
	ld.param.u64 	%rd14, [addmagnetoelasticfield_param_14];
	ld.param.f32 	%f52, [addmagnetoelasticfield_param_15];
	ld.param.u64 	%rd15, [addmagnetoelasticfield_param_16];
	ld.param.f32 	%f49, [addmagnetoelasticfield_param_17];
	ld.param.u32 	%r2, [addmagnetoelasticfield_param_18];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_10;

	cvta.to.global.u64 	%rd16, %rd7;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.nc.f32 	%f1, [%rd18];
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd17;
	ld.global.nc.f32 	%f2, [%rd20];
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd17;
	ld.global.nc.f32 	%f3, [%rd22];
	cvta.to.global.u64 	%rd23, %rd10;
	add.s64 	%rd24, %rd23, %rd17;
	ld.global.nc.f32 	%f4, [%rd24];
	cvta.to.global.u64 	%rd25, %rd12;
	add.s64 	%rd26, %rd25, %rd17;
	ld.global.nc.f32 	%f5, [%rd26];
	cvta.to.global.u64 	%rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd17;
	ld.global.nc.f32 	%f6, [%rd28];
	setp.eq.s64	%p2, %rd15, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd29, %rd15;
	add.s64 	%rd31, %rd29, %rd17;
	ld.global.nc.f32 	%f18, [%rd31];
	mul.f32 	%f49, %f18, %f49;

BB0_3:
	setp.eq.f32	%p3, %f49, 0f00000000;
	mov.f32 	%f50, 0f00000000;
	@%p3 bra 	BB0_5;

	rcp.rn.f32 	%f50, %f49;

BB0_5:
	setp.eq.s64	%p4, %rd13, 0;
	@%p4 bra 	BB0_7;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd17;
	ld.global.nc.f32 	%f20, [%rd34];
	mul.f32 	%f51, %f20, %f51;

BB0_7:
	setp.eq.s64	%p5, %rd14, 0;
	@%p5 bra 	BB0_9;

	cvta.to.global.u64 	%rd35, %rd14;
	add.s64 	%rd37, %rd35, %rd17;
	ld.global.nc.f32 	%f21, [%rd37];
	mul.f32 	%f52, %f21, %f52;

BB0_9:
	cvta.to.global.u64 	%rd38, %rd4;
	add.s64 	%rd40, %rd38, %rd17;
	cvta.to.global.u64 	%rd41, %rd5;
	add.s64 	%rd42, %rd41, %rd17;
	cvta.to.global.u64 	%rd43, %rd6;
	add.s64 	%rd44, %rd43, %rd17;
	mul.f32 	%f22, %f50, %f51;
	fma.rn.f32 	%f23, %f50, %f51, %f22;
	ld.global.nc.f32 	%f24, [%rd40];
	mul.f32 	%f25, %f23, %f24;
	ld.global.nc.f32 	%f26, [%rd42];
	ld.global.nc.f32 	%f27, [%rd44];
	mul.f32 	%f28, %f5, %f27;
	fma.rn.f32 	%f29, %f4, %f26, %f28;
	mul.f32 	%f30, %f50, %f52;
	mul.f32 	%f31, %f30, %f29;
	fma.rn.f32 	%f32, %f1, %f25, %f31;
	cvta.to.global.u64 	%rd45, %rd1;
	add.s64 	%rd46, %rd45, %rd17;
	ld.global.f32 	%f33, [%rd46];
	sub.f32 	%f34, %f33, %f32;
	st.global.f32 	[%rd46], %f34;
	mul.f32 	%f35, %f23, %f26;
	mul.f32 	%f36, %f6, %f27;
	fma.rn.f32 	%f37, %f4, %f24, %f36;
	mul.f32 	%f38, %f30, %f37;
	fma.rn.f32 	%f39, %f2, %f35, %f38;
	cvta.to.global.u64 	%rd47, %rd2;
	add.s64 	%rd48, %rd47, %rd17;
	ld.global.f32 	%f40, [%rd48];
	sub.f32 	%f41, %f40, %f39;
	st.global.f32 	[%rd48], %f41;
	mul.f32 	%f42, %f23, %f27;
	mul.f32 	%f43, %f6, %f26;
	fma.rn.f32 	%f44, %f5, %f24, %f43;
	mul.f32 	%f45, %f30, %f44;
	fma.rn.f32 	%f46, %f3, %f42, %f45;
	cvta.to.global.u64 	%rd49, %rd3;
	add.s64 	%rd50, %rd49, %rd17;
	ld.global.f32 	%f47, [%rd50];
	sub.f32 	%f48, %f47, %f46;
	st.global.f32 	[%rd50], %f48;

BB0_10:
	ret;
}


`
   addmagnetoelasticfield_ptx_75 = `
.version 6.3
.target sm_75
.address_size 64

	// .globl	addmagnetoelasticfield

.visible .entry addmagnetoelasticfield(
	.param .u64 addmagnetoelasticfield_param_0,
	.param .u64 addmagnetoelasticfield_param_1,
	.param .u64 addmagnetoelasticfield_param_2,
	.param .u64 addmagnetoelasticfield_param_3,
	.param .u64 addmagnetoelasticfield_param_4,
	.param .u64 addmagnetoelasticfield_param_5,
	.param .u64 addmagnetoelasticfield_param_6,
	.param .u64 addmagnetoelasticfield_param_7,
	.param .u64 addmagnetoelasticfield_param_8,
	.param .u64 addmagnetoelasticfield_param_9,
	.param .u64 addmagnetoelasticfield_param_10,
	.param .u64 addmagnetoelasticfield_param_11,
	.param .u64 addmagnetoelasticfield_param_12,
	.param .f32 addmagnetoelasticfield_param_13,
	.param .u64 addmagnetoelasticfield_param_14,
	.param .f32 addmagnetoelasticfield_param_15,
	.param .u64 addmagnetoelasticfield_param_16,
	.param .f32 addmagnetoelasticfield_param_17,
	.param .u32 addmagnetoelasticfield_param_18
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<53>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<51>;


	ld.param.u64 	%rd1, [addmagnetoelasticfield_param_0];
	ld.param.u64 	%rd2, [addmagnetoelasticfield_param_1];
	ld.param.u64 	%rd3, [addmagnetoelasticfield_param_2];
	ld.param.u64 	%rd4, [addmagnetoelasticfield_param_3];
	ld.param.u64 	%rd5, [addmagnetoelasticfield_param_4];
	ld.param.u64 	%rd6, [addmagnetoelasticfield_param_5];
	ld.param.u64 	%rd7, [addmagnetoelasticfield_param_6];
	ld.param.u64 	%rd8, [addmagnetoelasticfield_param_7];
	ld.param.u64 	%rd9, [addmagnetoelasticfield_param_8];
	ld.param.u64 	%rd10, [addmagnetoelasticfield_param_9];
	ld.param.u64 	%rd11, [addmagnetoelasticfield_param_10];
	ld.param.u64 	%rd12, [addmagnetoelasticfield_param_11];
	ld.param.u64 	%rd13, [addmagnetoelasticfield_param_12];
	ld.param.f32 	%f51, [addmagnetoelasticfield_param_13];
	ld.param.u64 	%rd14, [addmagnetoelasticfield_param_14];
	ld.param.f32 	%f52, [addmagnetoelasticfield_param_15];
	ld.param.u64 	%rd15, [addmagnetoelasticfield_param_16];
	ld.param.f32 	%f49, [addmagnetoelasticfield_param_17];
	ld.param.u32 	%r2, [addmagnetoelasticfield_param_18];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_10;

	cvta.to.global.u64 	%rd16, %rd7;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.nc.f32 	%f1, [%rd18];
	cvta.to.global.u64 	%rd19, %rd8;
	add.s64 	%rd20, %rd19, %rd17;
	ld.global.nc.f32 	%f2, [%rd20];
	cvta.to.global.u64 	%rd21, %rd9;
	add.s64 	%rd22, %rd21, %rd17;
	ld.global.nc.f32 	%f3, [%rd22];
	cvta.to.global.u64 	%rd23, %rd10;
	add.s64 	%rd24, %rd23, %rd17;
	ld.global.nc.f32 	%f4, [%rd24];
	cvta.to.global.u64 	%rd25, %rd12;
	add.s64 	%rd26, %rd25, %rd17;
	ld.global.nc.f32 	%f5, [%rd26];
	cvta.to.global.u64 	%rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd17;
	ld.global.nc.f32 	%f6, [%rd28];
	setp.eq.s64	%p2, %rd15, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd29, %rd15;
	add.s64 	%rd31, %rd29, %rd17;
	ld.global.nc.f32 	%f18, [%rd31];
	mul.f32 	%f49, %f18, %f49;

BB0_3:
	setp.eq.f32	%p3, %f49, 0f00000000;
	mov.f32 	%f50, 0f00000000;
	@%p3 bra 	BB0_5;

	rcp.rn.f32 	%f50, %f49;

BB0_5:
	setp.eq.s64	%p4, %rd13, 0;
	@%p4 bra 	BB0_7;

	cvta.to.global.u64 	%rd32, %rd13;
	add.s64 	%rd34, %rd32, %rd17;
	ld.global.nc.f32 	%f20, [%rd34];
	mul.f32 	%f51, %f20, %f51;

BB0_7:
	setp.eq.s64	%p5, %rd14, 0;
	@%p5 bra 	BB0_9;

	cvta.to.global.u64 	%rd35, %rd14;
	add.s64 	%rd37, %rd35, %rd17;
	ld.global.nc.f32 	%f21, [%rd37];
	mul.f32 	%f52, %f21, %f52;

BB0_9:
	cvta.to.global.u64 	%rd38, %rd4;
	add.s64 	%rd40, %rd38, %rd17;
	cvta.to.global.u64 	%rd41, %rd5;
	add.s64 	%rd42, %rd41, %rd17;
	cvta.to.global.u64 	%rd43, %rd6;
	add.s64 	%rd44, %rd43, %rd17;
	mul.f32 	%f22, %f50, %f51;
	fma.rn.f32 	%f23, %f50, %f51, %f22;
	ld.global.nc.f32 	%f24, [%rd40];
	mul.f32 	%f25, %f23, %f24;
	ld.global.nc.f32 	%f26, [%rd42];
	ld.global.nc.f32 	%f27, [%rd44];
	mul.f32 	%f28, %f5, %f27;
	fma.rn.f32 	%f29, %f4, %f26, %f28;
	mul.f32 	%f30, %f50, %f52;
	mul.f32 	%f31, %f30, %f29;
	fma.rn.f32 	%f32, %f1, %f25, %f31;
	cvta.to.global.u64 	%rd45, %rd1;
	add.s64 	%rd46, %rd45, %rd17;
	ld.global.f32 	%f33, [%rd46];
	sub.f32 	%f34, %f33, %f32;
	st.global.f32 	[%rd46], %f34;
	mul.f32 	%f35, %f23, %f26;
	mul.f32 	%f36, %f6, %f27;
	fma.rn.f32 	%f37, %f4, %f24, %f36;
	mul.f32 	%f38, %f30, %f37;
	fma.rn.f32 	%f39, %f2, %f35, %f38;
	cvta.to.global.u64 	%rd47, %rd2;
	add.s64 	%rd48, %rd47, %rd17;
	ld.global.f32 	%f40, [%rd48];
	sub.f32 	%f41, %f40, %f39;
	st.global.f32 	[%rd48], %f41;
	mul.f32 	%f42, %f23, %f27;
	mul.f32 	%f43, %f6, %f26;
	fma.rn.f32 	%f44, %f5, %f24, %f43;
	mul.f32 	%f45, %f30, %f44;
	fma.rn.f32 	%f46, %f3, %f42, %f45;
	cvta.to.global.u64 	%rd49, %rd3;
	add.s64 	%rd50, %rd49, %rd17;
	ld.global.f32 	%f47, [%rd50];
	sub.f32 	%f48, %f47, %f46;
	st.global.f32 	[%rd50], %f48;

BB0_10:
	ret;
}


`
 )
